### Datetime Functions
These functions help in parsing, manipulating, and analyzing datetime values.

In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('Ecomm_Sales.csv')

In [4]:
df.head()

,order_id,order_date,customer_id,product_category,region,quantity,unit_price,discount,payment_method,delivery_days,customer_rating,revenue
0,10001,1/1/2022,1102,Beauty,South,7,373.65,0.28,Wallet,10,4.7,1883.20
1,10002,1/2/2022,1435,Clothing,South,7,47.74,0.09,Card,6,3.9,304.10
2,10003,1/3/2022,1860,Beauty,East,3,311.28,0.31,COD,6,2.5,644.35
3,10004,1/4/2022,1270,Electronics,West,5,524.47,0.02,Wallet,6,1.6,2569.90
4,10005,1/5/2022,1106,Clothing,West,5,139.87,0.33,Wallet,4,4.9,468.56

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   order_id          5000 non-null   int64
 1   order_date        5000 non-null   object
 2   customer_id       5000 non-null   int64
 3   product_category  5000 non-null   object
 4   region            5000 non-null   object
 5   quantity          5000 non-null   int64
 6   unit_price        5000 non-null   float64
 7   discount          5000 non-null   float64
 8   payment_method    5000 non-null   object
 9   delivery_days     5000 non-null   int64
 10  customer_rating   5000 non-null   float64
 11  revenue           5000 non-null   float64
dtypes: float64(4), int64(4), object(4)
memory usage: 468.9+ KB

In [7]:
df['order_date'] = pd.to_datetime(df['order_date'])

In [8]:
df.head()

,order_id,order_date,customer_id,product_category,region,quantity,unit_price,discount,payment_method,delivery_days,customer_rating,revenue
0,10001,2022-01-01,1102,Beauty,South,7,373.65,0.28,Wallet,10,4.7,1883.20
1,10002,2022-01-02,1435,Clothing,South,7,47.74,0.09,Card,6,3.9,304.10
2,10003,2022-01-03,1860,Beauty,East,3,311.28,0.31,COD,6,2.5,644.35
3,10004,2022-01-04,1270,Electronics,West,5,524.47,0.02,Wallet,6,1.6,2569.90
4,10005,2022-01-05,1106,Clothing,West,5,139.87,0.33,Wallet,4,4.9,468.56

In [9]:
df.dtypes

order_id                     int64
order_date          datetime64[ns]
customer_id                  int64
product_category            object
region                      object
quantity                     int64
unit_price                 float64
discount                   float64
payment_method              object
delivery_days                int64
customer_rating            float64
revenue                    float64
dtype: object

In [12]:
row = df['order_date'][0]
row

Timestamp('2022-01-01 00:00:00')

In [14]:
row.year                 # prints the year from the date

2022

In [18]:
row.month                # prints the month from the date

1

In [21]:
row.day                  # prints the day from the date

1

In [22]:
row.hour                 # prints the hour

0

In [24]:
row.minute               # prints the minute

0

In [26]:
row.second               # prints the second

0

We can use this data from the columns as a whole using .dt object

In [32]:
df['order_date'].dt

In [33]:
df['order_date'].dt.year

0       2022
1       2022
2       2022
3       2022
4       2022
        ...
4995    2035
4996    2035
4997    2035
4998    2035
4999    2035
Name: order_date, Length: 5000, dtype: int32

In [34]:
df['order_date'].dt.month

0       1
1       1
2       1
3       1
4       1
       ..
4995    9
4996    9
4997    9
4998    9
4999    9
Name: order_date, Length: 5000, dtype: int32

In [35]:
df['order_date'].dt.day

0       1
1       2
2       3
3       4
4       5
       ..
4995    5
4996    6
4997    7
4998    8
4999    9
Name: order_date, Length: 5000, dtype: int32

Creating a new year column

In [36]:
df['year'] = df['order_date'].dt.year

In [37]:
df.head()

,order_id,order_date,customer_id,product_category,region,quantity,unit_price,discount,payment_method,delivery_days,customer_rating,revenue,year
0,10001,2022-01-01,1102,Beauty,South,7,373.65,0.28,Wallet,10,4.7,1883.20,2022
1,10002,2022-01-02,1435,Clothing,South,7,47.74,0.09,Card,6,3.9,304.10,2022
2,10003,2022-01-03,1860,Beauty,East,3,311.28,0.31,COD,6,2.5,644.35,2022
3,10004,2022-01-04,1270,Electronics,West,5,524.47,0.02,Wallet,6,1.6,2569.90,2022
4,10005,2022-01-05,1106,Clothing,West,5,139.87,0.33,Wallet,4,4.9,468.56,2022

#### strftime (stringformat time)
It is used to modify the datetime format

In [42]:
row = df['order_date'][0]
row

Timestamp('2022-01-01 00:00:00')

In [45]:
row.strftime('%Y')

'2022'

In [46]:
row.strftime('%m')

'01'

In [47]:
row.strftime('%d')

'01'

In [48]:
row.strftime('%m-%d')

'01-01'

In [49]:
row.strftime('%d/%m/%Y')

'01/01/2022'

In [51]:
row.strftime('%B')        # %B --> displays the month name

'January'

In [55]:
df['order_date'][100].strftime('%B')

'April'

A comprehensive list of other formats can be found here: <br>
https://pandas.pydata.org/docs/reference/api/pandas.Period.strftime.html

Thus, strftime() is used to display datetime information in a specific, human-readable format, especially when generating reports, creating user-friendly visualizations, or exporting data.

In [57]:
df['order_date'][100].strftime('%A')

'Monday'