## Bag of Words

### Binary Bag of Words

In [1]:
import re
import pandas as pd
import numpy as np

### Scratch Implementation

In [2]:
dataset = [
    ("You won a prize! Claim now.", 'spam'),
    ("Meeting tomorrow at 5 PM. Don't forget!", "not spam"),
    ("Win big now! Claim your prize.", 'spam'),
    ("Buy now! Lowest price available.", 'spam'),
    ("Claim your prize now!", 'spam'),
    ("Submit the project by Friday.", "not spam"),
    ("You won an iPhone! Get it now.", 'spam'),
    ("Attached is the report.", "not spam"),
    ("Reset your password here.", "spam"),
    ("Are we still going to the gym?", "not spam"),
    ("Send me the files today.", "not spam"),
    ("Limited stock! Buy now.", "spam"),
    ("See you tomorrow at 5 PM.", "not spam"),
    ("Claim your free vacation now.", "spam"),
    ("Check holiday deals today.", "spam"),
    ("Looking forward to our meeting.", "not spam"),
    ("Bring documents for tomorrow.", "not spam"),
    ("Lowest prices! Buy today.", "spam"),
    ("Gym session is at 6 AM.", "not spam"),
    ("Let's have lunch this weekend.", "not spam"),
    ("Claim your car prize now.", "spam"),
    ("Here’s the latest report.", "not spam"),
    ("Earn money from home now.", "spam"),
    ("Please confirm the meeting time.", "not spam"),
    ("30% off! Buy today.", "spam"),
    ("Win big with this survey.", "spam"),
    ("Catch up for lunch soon.", "not spam"),
    ("Loan approved! Get details here.", "spam"),
    ("See you at 9 AM for review.", "not spam"),
    ("Your free iPhone is waiting.", "spam"),
]

In [3]:
text = [i for i,j in dataset]
label = [j for i,j in dataset]

In [4]:
text[:10]

['You won a prize! Claim now.',
 "Meeting tomorrow at 5 PM. Don't forget!",
 'Win big now! Claim your prize.',
 'Buy now! Lowest price available.',
 'Claim your prize now!',
 'Submit the project by Friday.',
 'You won an iPhone! Get it now.',
 'Attached is the report.',
 'Reset your password here.',
 'Are we still going to the gym?']

In [5]:
label[:10]

['spam',
 'not spam',
 'spam',
 'spam',
 'spam',
 'not spam',
 'spam',
 'not spam',
 'spam',
 'not spam']

In [6]:
len(dataset)

30

In [7]:
df = pd.DataFrame(dataset, columns=['Sentence', 'Label'])
df.head()

                                  Sentence     Label
0              You won a prize! Claim now.      spam
1  Meeting tomorrow at 5 PM. Don't forget!  not spam
2           Win big now! Claim your prize.      spam
3         Buy now! Lowest price available.      spam
4                    Claim your prize now!      spam

In [ ]:
def tokenize(sentence):
    sentence = sentence.lower() 
    sentence = re.sub(r'[^\w\s]', '', sentence)        # \w is for A-Z,a-z,0-9, _, \s is for space, ^ - not condition
    return sentence.split()

In [5]:
# string = 'I #like pizza!! I enjoy @eating it. I will go for having the pizza at 3 p.m. today.'
# re.sub(r'[^\w\s]', '', string.lower()).split()

In [10]:
tokenized_sentences = [tokenize(t) for t in text]
tokenized_sentences[:5]

[['you', 'won', 'a', 'prize', 'claim', 'now'],
 ['meeting', 'tomorrow', 'at', '5', 'pm', 'dont', 'forget'],
 ['win', 'big', 'now', 'claim', 'your', 'prize'],
 ['buy', 'now', 'lowest', 'price', 'available'],
 ['claim', 'your', 'prize', 'now']]

In [ ]:
def build_vocabulary(sentences):
    vocabulary = set()
    for word in sentences:
        vocabulary.update(word)
    return sorted(list(vocabulary))

In [12]:
vocabulary = build_vocabulary(tokenized_sentences)
vocabulary

['30',
 '5',
 '6',
 '9',
 'a',
 'am',
 'an',
 'approved',
 'are',
 'at',
 'attached',
 'available',
 'big',
 'bring',
 'buy',
 'by',
 'car',
 'catch',
 'check',
 'claim',
 'confirm',
 'deals',
 'details',
 'documents',
 'dont',
 'earn',
 'files',
 'for',
 'forget',
 'forward',
 'free',
 'friday',
 'from',
 'get',
 'going',
 'gym',
 'have',
 'here',
 'heres',
 'holiday',
 'home',
 'iphone',
 'is',
 'it',
 'latest',
 'lets',
 'limited',
 'loan',
 'looking',
 'lowest',
 'lunch',
 'me',
 'meeting',
 'money',
 'now',
 'off',
 'our',
 'password',
 'please',
 'pm',
 'price',
 'prices',
 'prize',
 'project',
 'report',
 'reset',
 'review',
 'see',
 'send',
 'session',
 'soon',
 'still',
 'stock',
 'submit',
 'survey',
 'the',
 'this',
 'time',
 'to',
 'today',
 'tomorrow',
 'up',
 'vacation',
 'waiting',
 'we',
 'weekend',
 'win',
 'with',
 'won',
 'you',
 'your']

In [13]:
len(vocabulary)

91

In [14]:
def create_bow_vector(sentence, vocabulary): 
    vec = [0]*len(vocabulary)
    for word in sentence:
        if word in vocabulary:
            idx = vocabulary.index(word)
            vec[idx] = 1
    return vec

In [15]:
bow_vectors = [create_bow_vector(sentence, vocabulary) for sentence in tokenized_sentences]
# bow_vectors[0]

In [16]:
len(bow_vectors)

30

In [17]:
encoded_vectors = np.array(bow_vectors)
encoded_vectors[0]

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 0])

In [18]:
cols = [i for i in vocabulary]

In [19]:
df[cols] = encoded_vectors

In [20]:
df.head()

,Sentence,Label,30,5,6,9,a,am,an,approved,...,up,vacation,waiting,we,weekend,win,with,won,you,your
0,You won a prize! Claim now.,spam,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,1,1,0
1,Meeting tomorrow at 5 PM. Don't forget!,not spam,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,Win big now! Claim your prize.,spam,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,1
3,Buy now! Lowest price available.,spam,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,Claim your prize now!,spam,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 93 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Sentence   30 non-null     object
 1   Label      30 non-null     object
 2   30         30 non-null     int32
 3   5          30 non-null     int32
 4   6          30 non-null     int32
 5   9          30 non-null     int32
 6   a          30 non-null     int32
 7   am         30 non-null     int32
 8   an         30 non-null     int32
 9   approved   30 non-null     int32
 10  are        30 non-null     int32
 11  at         30 non-null     int32
 12  attached   30 non-null     int32
 13  available  30 non-null     int32
 14  big        30 non-null     int32
 15  bring      30 non-null     int32
 16  buy        30 non-null     int32
 17  by         30 non-null     int32
 18  car        30 non-null     int32
 19  catch      30 non-null     int32
 20  check      30 non-null     int32
 21  claim      30 non-null     int32
 22  confirm    30 non-null     int32
 23  deals      30 non-null     int32
 24  details    30 non-null     int32
 25  documents  30 non-null     int32
 26  dont       30 non-null     int32
 27  earn       30 non-null     int32
 28  files      30 non-null     int32
 29  for        30 non-null     int32
 30  forget     30 non-null     int32
 31  forward    30 non-null     int32
 32  free       30 non-null     int32
 33  friday     30 non-null     int32
 34  from       30 non-null     int32
 35  get        30 non-null     int32
 36  going      30 non-null     int32
 37  gym        30 non-null     int32
 38  have       30 non-null     int32
 39  here       30 non-null     int32
 40  heres      30 non-null     int32
 41  holiday    30 non-null     int32
 42  home       30 non-null     int32
 43  iphone     30 non-null     int32
 44  is         30 non-null     int32
 45  it         30 non-null     int32
 46  latest     30 non-null     int32
 47  lets       30 non-null     int32
 48  limited    30 non-null     int32
 49  loan       30 non-null     int32
 50  looking    30 non-null     int32
 51  lowest     30 non-null     int32
 52  lunch      30 non-null     int32
 53  me         30 non-null     int32
 54  meeting    30 non-null     int32
 55  money      30 non-null     int32
 56  now        30 non-null     int32
 57  off        30 non-null     int32
 58  our        30 non-null     int32
 59  password   30 non-null     int32
 60  please     30 non-null     int32
 61  pm         30 non-null     int32
 62  price      30 non-null     int32
 63  prices     30 non-null     int32
 64  prize      30 non-null     int32
 65  project    30 non-null     int32
 66  report     30 non-null     int32
 67  reset      30 non-null     int32
 68  review     30 non-null     int32
 69  see        30 non-null     int32
 70  send       30 non-null     int32
 71  session    30 non-null     int32
 72  soon       30 non-null     int32
 73  still      30 non-null     int32
 74  stock      30 non-null     int32
 75  submit     30 non-null     int32
 76  survey     30 non-null     int32
 77  the        30 non-null     int32
 78  this       30 non-null     int32
 79  time       30 non-null     int32
 80  to         30 non-null     int32
 81  today      30 non-null     int32
 82  tomorrow   30 non-null     int32
 83  up         30 non-null     int32
 84  vacation   30 non-null     int32
 85  waiting    30 non-null     int32
 86  we         30 non-null     int32
 87  weekend    30 non-null     int32
 88  win        30 non-null     int32
 89  with       30 non-null     int32
 90  won        30 non-null     int32
 91  you        30 non-null     int32
 92  your       30 non-null     int32
dtypes: int32(91), object(2)
memory usage: 11.3+ KB

### Using sk-learn

In [22]:
from sklearn.feature_extraction.text import CountVectorizer

In [23]:
texts = [text for text, label in dataset]
labels = [label for text, label in dataset]

In [24]:
vectorizer = CountVectorizer()

In [25]:
bow_matrix = vectorizer.fit_transform(texts)

In [26]:
bow_matrix

<30x86 sparse matrix of type '<class 'numpy.int64'>'
	with 148 stored elements in Compressed Sparse Row format>

In [27]:
bow_matrix.toarray()

array([[0, 0, 0, ..., 1, 1, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 1],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 1, 0],
       [0, 0, 0, ..., 0, 0, 1]], dtype=int64)

In [28]:
vectorizer.get_feature_names_out()

array(['30', 'am', 'an', 'approved', 'are', 'at', 'attached', 'available',
       'big', 'bring', 'buy', 'by', 'car', 'catch', 'check', 'claim',
       'confirm', 'deals', 'details', 'documents', 'don', 'earn', 'files',
       'for', 'forget', 'forward', 'free', 'friday', 'from', 'get',
       'going', 'gym', 'have', 'here', 'holiday', 'home', 'iphone', 'is',
       'it', 'latest', 'let', 'limited', 'loan', 'looking', 'lowest',
       'lunch', 'me', 'meeting', 'money', 'now', 'off', 'our', 'password',
       'please', 'pm', 'price', 'prices', 'prize', 'project', 'report',
       'reset', 'review', 'see', 'send', 'session', 'soon', 'still',
       'stock', 'submit', 'survey', 'the', 'this', 'time', 'to', 'today',
       'tomorrow', 'up', 'vacation', 'waiting', 'we', 'weekend', 'win',
       'with', 'won', 'you', 'your'], dtype=object)

In [29]:
bow_df = pd.DataFrame(bow_matrix.toarray(), columns=vectorizer.get_feature_names_out())

In [30]:
bow_df['label'] = labels

In [31]:
bow_df.head()

,30,am,an,approved,are,at,attached,available,big,bring,...,vacation,waiting,we,weekend,win,with,won,you,your,label
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,1,0,spam
1,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,not spam
2,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,1,0,0,0,1,spam
3,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,spam
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,spam