In [259]:
import pandas as pd
import seaborn as sns

import warnings
warnings.filterwarnings('ignore')

In [299]:
df = sns.load_dataset('tips')

In [300]:
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

#### Grouping the DataFrame based on Gender

In [262]:
df.groupby('sex')

In [263]:
# Displaying the total groups created
df.groupby('sex').ngroups

2

In [264]:
# Display total groups
df.groupby('sex').groups

{'Male': [1, 2, 3, 5, 6, 7, 8, 9, 10, 12, 13, 15, 17, 19, 20, 23, 24, 25, 26, 27, 28, 30, 31, 34, 35, 36, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 53, 54, 55, 56, 58, 59, 60, 61, 62, 63, 64, 65, 68, 69, 70, 75, 76, 77, 78, 79, 80, 81, 83, 84, 86, 87, 88, 89, 90, 91, 95, 96, 97, 98, 99, 105, 106, 107, 108, 110, 112, 113, 116, 120, 122, 123, 126, 129, 130, 138, 141, 142, 148, 149, 150, 151, 152, 153, 154, 156, 159, ...], 'Female': [0, 4, 11, 14, 16, 18, 21, 22, 29, 32, 33, 37, 51, 52, 57, 66, 67, 71, 72, 73, 74, 82, 85, 92, 93, 94, 100, 101, 102, 103, 104, 109, 111, 114, 115, 117, 118, 119, 121, 124, 125, 127, 128, 131, 132, 133, 134, 135, 136, 137, 139, 140, 143, 144, 145, 146, 147, 155, 157, 158, 162, 164, 168, 169, 178, 186, 188, 191, 197, 198, 201, 202, 203, 205, 209, 213, 214, 215, 219, 221, 223, 225, 226, 229, 238, 240, 243]}

In [199]:
# Displaying group names
df.groupby('sex').groups.keys()

dict_keys(['Male', 'Female'])

##### Let us get the data for Male group

In [200]:
male_grp = df.groupby('sex').get_group('Male')

In [201]:
male_grp.head()

   total_bill   tip   sex smoker  day    time  size
1       10.34  1.66  Male     No  Sun  Dinner     3
2       21.01  3.50  Male     No  Sun  Dinner     3
3       23.68  3.31  Male     No  Sun  Dinner     2
5       25.29  4.71  Male     No  Sun  Dinner     4
6        8.77  2.00  Male     No  Sun  Dinner     2

In [202]:
male_grp.shape

(157, 7)

Ques. What is the average total bill paid by male customers?

In [204]:
male_grp['total_bill'].mean()

20.744076433121016

Ques. On which day the Male customers visit the restaurant the most?

In [206]:
male_grp['day'].mode()[0]

'Sat'

Ques. Which is the most preferred time for Males for dining out?

In [208]:
male_grp['time'].mode()[0]

'Dinner'

##### Get the data for Female group

In [209]:
female_grp = df.groupby('sex').get_group('Female')

In [210]:
female_grp.head()

    total_bill   tip     sex smoker  day    time  size
0        16.99  1.01  Female     No  Sun  Dinner     2
4        24.59  3.61  Female     No  Sun  Dinner     4
11       35.26  5.00  Female     No  Sun  Dinner     4
14       14.83  3.02  Female     No  Sun  Dinner     2
16       10.33  1.67  Female     No  Sun  Dinner     3

In [211]:
female_grp.shape

(87, 7)

Ques. What is the maximum total bill paid by a female customer?

In [213]:
female_grp['total_bill'].max()

44.3

Ques. Do most female customers smoke?

In [266]:
female_grp['smoker'].mode()[0]

'No'

Ans - No, most of the female customers does not smoke.

Ques. What is the maximum number of people who visited the restaurant ever with a female customer?

In [218]:
female_grp['size'].max()

6

Ques. What can be the total revenue generated by the restaurant on Sunday?

In [301]:
day = df.groupby('day')

In [302]:
sun_grp = day.get_group('Sun')
sun_grp['total_bill'].sum()

1627.16

Ques. How many total people visited the restaurant on Saturday & Sunday?

In [303]:
print('Total people visited the restaurant on Saturday:')
df.groupby('day').get_group('Sat')['size'].sum()

Total people visited the restaurant on Saturday:

219

In [304]:
print('Total people visited the restaurant on Sunday:')
df.groupby('day').get_group('Sun')['size'].sum()

Total people visited the restaurant on Sunday:

216

Ques. What is the maximum tip received at the restaurant on Friday?

In [305]:
df.groupby('day').get_group('Fri')['tip'].max()

4.73

#### Group by multiple columns

In [306]:
df.groupby(["sex", "smoker"])

In [307]:
df.groupby(["sex", "smoker"]).ngroups

4

In [308]:
df.groupby(["sex", "smoker"]).groups.keys()

dict_keys([('Female', 'No'), ('Female', 'Yes'), ('Male', 'No'), ('Male', 'Yes')])

Ques. Find the average total bill paid by each gender and smoker category.

In [309]:
group = df.groupby(['sex', 'smoker'])

In [310]:
group['total_bill'].mean()

sex     smoker
Male    Yes       22.284500
        No        19.791237
Female  Yes       17.977879
        No        18.105185
Name: total_bill, dtype: float64

Ques. Find the total number of customers in each gender and smoker category.

In [311]:
group['total_bill'].count()

sex     smoker
Male    Yes       60
        No        97
Female  Yes       33
        No        54
Name: total_bill, dtype: int64

#### Applying multiple statistical functions

Ques. What is the total and average bill paid by all smoker and non-smoker customers.

In [229]:
df.groupby('smoker').agg({'total_bill': ['sum', 'mean']})

       total_bill
              sum       mean
smoker
Yes       1930.34  20.756344
No        2897.43  19.188278

Ques. Find the total and average tip given by smokers and non-smokers.

In [230]:
df.groupby('smoker').agg({'tip': ['sum', 'mean']})

           tip
           sum      mean
smoker
Yes     279.81  3.008710
No      451.77  2.991854

Ques. Find the average, minimum and maximum tip for each day

In [231]:
# aggregate function can also be applied
df.groupby('day')['tip'].aggregate(['mean','min','max'])

          mean   min    max
day
Thur  2.771452  1.25   6.70
Fri   2.734737  1.00   4.73
Sat   2.993103  1.00  10.00
Sun   3.255132  1.01   6.50

Ques. Find the total and average bill paid by customers at each meal time.

In [232]:
df.groupby('time')['total_bill'].aggregate(['sum','mean'])

            sum       mean
time
Lunch   1167.47  17.168676
Dinner  3660.30  20.797159

Ques. Calculate the maximum bill and the average bill paid by all male and female customers who visited the restaurant individually for each meal (Lunch and Dinner).

In [315]:
df.groupby(['sex','time']).groups.keys()

dict_keys([('Female', 'Dinner'), ('Female', 'Lunch'), ('Male', 'Dinner'), ('Male', 'Lunch')])

In [316]:
df.groupby(['sex','time'])['total_bill'].aggregate(['max','mean'])

                 max       mean
sex    time
Male   Lunch   41.19  18.048485
       Dinner  50.81  21.461452
Female Lunch   43.11  16.339143
       Dinner  44.30  19.213077

Ques. Calculate the maximum bill, the average bill, the minimum tip and the total tip paid by all male and female customers who visited the restaurant individually for each meal (Lunch and Dinner).

In [317]:
df.groupby(['sex','time']).aggregate({'total_bill':['max','mean'], 'tip':['min','sum']})

              total_bill              tip
                     max       mean   min     sum
sex    time
Male   Lunch       41.19  18.048485  1.44   95.11
       Dinner      50.81  21.461452  1.00  389.96
Female Lunch       43.11  16.339143  1.25   90.40
       Dinner      44.30  19.213077  1.00  156.11

Ques. Group the data by day and calculate the minimum and maximum total bill, along with the total and average tip for each day.

In [314]:
df.groupby('day').aggregate({'total_bill':['min','max'], 'tip':['sum','mean']})

     total_bill            tip
            min    max     sum      mean
day
Thur       7.51  43.11  171.83  2.771452
Fri        5.75  40.17   51.96  2.734737
Sat        3.07  50.81  260.40  2.993103
Sun        7.25  48.17  247.39  3.255132

#### Cross Tabulation

In [267]:
# frequency table between gender and smoker column
pd.crosstab(df["sex"], df["smoker"])

smoker  Yes  No
sex
Male     60  97
Female   33  54

In [268]:
# normalize=True prints the percentage of values
pd.crosstab(df["sex"], df["smoker"], normalize=True)

smoker       Yes        No
sex
Male    0.245902  0.397541
Female  0.135246  0.221311

In [270]:
# Display gender wise how customers visit at each meal time
pd.crosstab(df["sex"], df["time"])

time    Lunch  Dinner
sex
Male       33     124
Female     35      52

#### Pivoting and Melting
- Pivot converts rows → columns
- Melt converts columns → rows

Let's create a DataFrame

In [271]:
data = {
        'Region': ['North', 'South', 'North', 'South', 'North', 'South'],
        'Product': ['A', 'A', 'B', 'B', 'C', 'C'],
        'Sales': [100, 200, 150, 300, 250, 400]
       }
df = pd.DataFrame(data)

In [239]:
df

  Region Product  Sales
0  North       A    100
1  South       A    200
2  North       B    150
3  South       B    300
4  North       C    250
5  South       C    400

To see the sales of each product in every region we use pivot method here.

In [240]:
df.pivot(index='Region', columns='Product', values='Sales')

Product    A    B    C
Region
North    100  150  250
South    200  300  400

- index - this decides what becomes rows
- columns - this decides what becomes the column headings
- values - this fills the table with values

The above result can be achieved using groupby() too, but pivot() is shorter and is designed specifically for reshaping the data

Ques. Find the total sales of each product.

In [272]:
pivot_df = df.pivot(index='Region', columns='Product', values='Sales')

In [273]:
pivot_df.sum()

Product
A    300
B    450
C    650
dtype: int64

Ques. Find the total sales of each region.

In [274]:
pivot_df.sum(axis=1)

Region
North    500
South    900
dtype: int64

Ques. Which product generated the highest total sales?

In [244]:
pivot_df.sum().idxmax()        # idxmax() - it returns the label (index) where the maximum value is found

'C'

Ques. Which region generated the highest total sales?

In [276]:
pivot_df.sum(axis=1).idxmax()

'South'

Ques. Calculate the grand total sales of all regions and all products.

In [278]:
pivot_df.sum().sum()

1400

##### Melt Method

In [279]:
pivot_df

Product    A    B    C
Region
North    100  150  250
South    200  300  400

In [280]:
pivot_df.reset_index()

Product Region    A    B    C
0        North  100  150  250
1        South  200  300  400

In [282]:
pivot_df_reset = pivot_df.reset_index()

Product Region    A    B    C
0        North  100  150  250
1        South  200  300  400

In [283]:
pivot_df_reset.melt(id_vars='Region', var_name='Product', value_name='Sales')

  Region Product  Sales
0  North       A    100
1  South       A    200
2  North       B    150
3  South       B    300
4  North       C    250
5  South       C    400

- As region is not a column and melt works with columns, therefore resetting the index first.
- id_vars: These columns remain unchanged and are repeated for every melted row.
- var_name: New column storing old column names.
- value_name: The new column that stores the values.

#### Stack and Unstack
- Stack is also used to convert columns into rows but it moves existing column labels into the row index.
- It produces a MultiIndex Series/DataFrame
- Once the data is stacked, it becomes a Series with a MultiIndex.

In [284]:
df.head()

  Region Product  Sales
0  North       A    100
1  South       A    200
2  North       B    150
3  South       B    300
4  North       C    250

In [286]:
stacked_df = df.stack()

In [287]:
stacked_df

0  Region     North
   Product        A
   Sales        100
1  Region     South
   Product        A
   Sales        200
2  Region     North
   Product        B
   Sales        150
3  Region     South
   Product        B
   Sales        300
4  Region     North
   Product        C
   Sales        250
5  Region     South
   Product        C
   Sales        400
dtype: object

In [288]:
type(stacked_df)

pandas.core.series.Series

In [289]:
stacked_df.index

MultiIndex([(0,  'Region'),
            (0, 'Product'),
            (0,   'Sales'),
            (1,  'Region'),
            (1, 'Product'),
            (1,   'Sales'),
            (2,  'Region'),
            (2, 'Product'),
            (2,   'Sales'),
            (3,  'Region'),
            (3, 'Product'),
            (3,   'Sales'),
            (4,  'Region'),
            (4, 'Product'),
            (4,   'Sales'),
            (5,  'Region'),
            (5, 'Product'),
            (5,   'Sales')],
           )

There are 2 index levels here:
- Level 0 → 0,1,2,3,4,5
- Level 1 → Region, Product, Sales

Ques. Find how many Region values are present.

In [290]:
stacked_df.xs('Region', level=1)

0    North
1    South
2    North
3    South
4    North
5    South
dtype: object

df.xs → It stands for Cross Section and is used to extract (select) data from a particular level of a MultiIndex.

Ques. Find all Product values.

In [254]:
stacked_df.xs('Product', level=1)

0    A
1    A
2    B
3    B
4    C
5    C
dtype: object

Ques. Find all Sales values.

In [291]:
stacked_df.xs('Sales', level=1)

0    100
1    200
2    150
3    300
4    250
5    400
dtype: object

Ques. Find the maximum sales value.

In [292]:
stacked_df.xs('Sales', level=1).max()

400

Ques. Find the count of each region.

In [295]:
stacked_df.xs('Region', level=1).value_counts()

North    3
South    3
Name: count, dtype: int64

#### Unstack Data

In [296]:
stacked_df.unstack()

  Region Product Sales
0  North       A   100
1  South       A   200
2  North       B   150
3  South       B   300
4  North       C   250
5  South       C   400