## Pandas - Python library used for working with dataframes

What is Pandas?

Pandas stands for Panel data or Python Data Analysis. It is a library used for data analysis and manipulation. It creates a dataframe that is nothing but data in tabular form. Pandas works with heterogenous data. A single column in pandas is called as series. Series in pandas is like a vector in numpy (single col)

What is a dataframe?

A DataFrame is a data structure that organizes data into a 2-dimensional table of rows and columns, much like a spreadsheet

#### Install Command - pip install pandas

Importing Pandas

In [1]:
import pandas as pd

#### Creating a Pandas series

In [4]:
data = pd.Series(100, index=[1,2,3,4,5,6,7,8,9,10])

In [5]:
data

1     100
2     100
3     100
4     100
5     100
6     100
7     100
8     100
9     100
10    100
dtype: int64

In [6]:
type(data)

pandas.core.series.Series

In [8]:
marks = pd.Series(data=[98,83,90,78,95], index=[1,2,3,4,5])

In [9]:
marks

1    98
2    83
3    90
4    78
5    95
dtype: int64

#### Dataframe creation using multiple forms of data

In [2]:
data = {
   'fruits': ['apple', 'mango', 'banana', 'kiwi', 'grapes', 'pear'],
   'animals': ['dog', 'cat', 'horse', 'rabbit', 'camel', 'elephant'],
   'places': ['mumbai', 'delhi', 'bangalore', 'kolkata', 'chennai', 'pune'],
   'vegetables': ['potato', 'tomato', 'brinjal', 'carrot', 'peas', 'raddish']
   }

In [3]:
data

{'fruits': ['apple', 'mango', 'banana', 'kiwi', 'grapes', 'pear'],
 'animals': ['dog', 'cat', 'horse', 'rabbit', 'camel', 'elephant'],
 'places': ['mumbai', 'delhi', 'bangalore', 'kolkata', 'chennai', 'pune'],
 'vegetables': ['potato', 'tomato', 'brinjal', 'carrot', 'peas', 'raddish']}

In [4]:
pd.DataFrame(data)

   fruits   animals     places vegetables
0   apple       dog     mumbai     potato
1   mango       cat      delhi     tomato
2  banana     horse  bangalore    brinjal
3    kiwi    rabbit    kolkata     carrot
4  grapes     camel    chennai       peas
5    pear  elephant       pune    raddish

In [5]:
Employee = [
   ('Ajay', 29, 35000, 'Mumbai'),
   ('Sumit', 34, 45000, 'Pune'),
   ('Ankit', 36, 31000, 'Delhi'),
   ('Amit', 44, 52000, 'Bangalore')
   ]

In [6]:
Employee

[('Ajay', 29, 35000, 'Mumbai'),
 ('Sumit', 34, 45000, 'Pune'),
 ('Ankit', 36, 31000, 'Delhi'),
 ('Amit', 44, 52000, 'Bangalore')]

In [7]:
pd.DataFrame(Employee, columns = ['Name', 'Age', 'Salary', 'City'])

    Name  Age  Salary       City
0   Ajay   29   35000     Mumbai
1  Sumit   34   45000       Pune
2  Ankit   36   31000      Delhi
3   Amit   44   52000  Bangalore

In [8]:
Employee = [
   {'Name':'Ajay', 'Age':34, 'Salary':30000, 'City':'Pune'},
   {'Name':'Amit', 'Age':29, 'Salary':36000, 'City':'Mumbai'},
   {'Name':'Ankit', 'Age':38, 'Salary':43000, 'City':'Bangalore'},
   {'Name':'Arpit', 'Age':40, 'Salary':49000, 'City':'Hyderabad'}
   ]

In [9]:
pd.DataFrame(Employee)

    Name  Age  Salary       City
0   Ajay   34   30000       Pune
1   Amit   29   36000     Mumbai
2  Ankit   38   43000  Bangalore
3  Arpit   40   49000  Hyderabad

Other than creating a DataFrame in pandas, we can also load the data from external files:
1. CSV
2. Excel
3. JSON
4. SQL

Excel and CSV are the most commonly used data sources

#### read_csv() - for loading a csv file into pandas

In [2]:
df = pd.read_csv('countries.csv')

In [3]:
df

          country  year  population continent  life_exp     gdp_cap
0     Afghanistan  1952     8425333      Asia    28.801  779.445314
1     Afghanistan  1957     9240934      Asia    30.332  820.853030
2     Afghanistan  1962    10267083      Asia    31.997  853.100710
3     Afghanistan  1967    11537966      Asia    34.020  836.197138
4     Afghanistan  1972    13079460      Asia    36.088  739.981106
...           ...   ...         ...       ...       ...         ...
1699     Zimbabwe  1987     9216418    Africa    62.351  706.157306
1700     Zimbabwe  1992    10704340    Africa    60.377  693.420786
1701     Zimbabwe  1997    11404948    Africa    46.809  792.449960
1702     Zimbabwe  2002    11926563    Africa    39.989  672.038623
1703     Zimbabwe  2007    12311143    Africa    43.487  469.709298

[1704 rows x 6 columns]

In [13]:
# type - to print the type of df
type(df)

pandas.core.frame.DataFrame

In [14]:
# .head() - to print the top 5 rows
df.head()

       country  year  population continent  life_exp     gdp_cap
0  Afghanistan  1952     8425333      Asia    28.801  779.445314
1  Afghanistan  1957     9240934      Asia    30.332  820.853030
2  Afghanistan  1962    10267083      Asia    31.997  853.100710
3  Afghanistan  1967    11537966      Asia    34.020  836.197138
4  Afghanistan  1972    13079460      Asia    36.088  739.981106

In [15]:
# .head() - can also be used to print the top selected number of rows
df.head(2)

       country  year  population continent  life_exp     gdp_cap
0  Afghanistan  1952     8425333      Asia    28.801  779.445314
1  Afghanistan  1957     9240934      Asia    30.332  820.853030

In [16]:
# .tail() - prints the bottom 5 rows
df.tail()

       country  year  population continent  life_exp     gdp_cap
1699  Zimbabwe  1987     9216418    Africa    62.351  706.157306
1700  Zimbabwe  1992    10704340    Africa    60.377  693.420786
1701  Zimbabwe  1997    11404948    Africa    46.809  792.449960
1702  Zimbabwe  2002    11926563    Africa    39.989  672.038623
1703  Zimbabwe  2007    12311143    Africa    43.487  469.709298

In [17]:
# .tail() - can also be used to print the bottom selected number of rows
df.tail(10)

       country  year  population continent  life_exp     gdp_cap
1694  Zimbabwe  1962     4277736    Africa    52.358  527.272182
1695  Zimbabwe  1967     4995432    Africa    53.995  569.795071
1696  Zimbabwe  1972     5861135    Africa    55.635  799.362176
1697  Zimbabwe  1977     6642107    Africa    57.674  685.587682
1698  Zimbabwe  1982     7636524    Africa    60.363  788.855041
1699  Zimbabwe  1987     9216418    Africa    62.351  706.157306
1700  Zimbabwe  1992    10704340    Africa    60.377  693.420786
1701  Zimbabwe  1997    11404948    Africa    46.809  792.449960
1702  Zimbabwe  2002    11926563    Africa    39.989  672.038623
1703  Zimbabwe  2007    12311143    Africa    43.487  469.709298

In [18]:
# with info we can check the summary of the dataframe
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1704 entries, 0 to 1703
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   country     1704 non-null   object
 1   year        1704 non-null   int64
 2   population  1704 non-null   int64
 3   continent   1704 non-null   object
 4   life_exp    1704 non-null   float64
 5   gdp_cap     1704 non-null   float64
dtypes: float64(2), int64(2), object(2)
memory usage: 80.0+ KB

All numerical columns are of either int or float data type but all categorical columns are of object data type.

In [19]:
# this prints the shape of df - (rows, columns)
df.shape

(1704, 6)

In [20]:
# .index - used to print the range of index for the dataframe
df.index

RangeIndex(start=0, stop=1704, step=1)

In [21]:
# .size() - prints the size of dataframe
df.size

10224

In [22]:
# this prints the statistical summary of the df (for all numerical column)
df.describe()

             year    population     life_exp        gdp_cap
count  1704.00000  1.704000e+03  1704.000000    1704.000000
mean   1979.50000  2.960121e+07    59.474439    7215.327081
std      17.26533  1.061579e+08    12.917107    9857.454543
min    1952.00000  6.001100e+04    23.599000     241.165876
25%    1965.75000  2.793664e+06    48.198000    1202.060309
50%    1979.50000  7.023596e+06    60.712500    3531.846988
75%    1993.25000  1.958522e+07    70.845500    9325.462346
max    2007.00000  1.318683e+09    82.603000  113523.132900

In [23]:
# include='all' includes all the data type columns
df.describe(include='all')

,country,year,population,continent,life_exp,gdp_cap
count,1704,1704.00000,1.704000e+03,1704,1704.000000,1704.000000
unique,142,NaN,NaN,5,NaN,NaN
top,Afghanistan,NaN,NaN,Africa,NaN,NaN
freq,12,NaN,NaN,624,NaN,NaN
mean,NaN,1979.50000,2.960121e+07,NaN,59.474439,7215.327081
std,NaN,17.26533,1.061579e+08,NaN,12.917107,9857.454543
min,NaN,1952.00000,6.001100e+04,NaN,23.599000,241.165876
25%,NaN,1965.75000,2.793664e+06,NaN,48.198000,1202.060309
50%,NaN,1979.50000,7.023596e+06,NaN,60.712500,3531.846988
75%,NaN,1993.25000,1.958522e+07,NaN,70.845500,9325.462346
max,NaN,2007.00000,1.318683e+09,NaN,82.603000,113523.132900

How to access the elements of a Series/Particlular column?

In [24]:
df['country']

0       Afghanistan
1       Afghanistan
2       Afghanistan
3       Afghanistan
4       Afghanistan
           ...
1699       Zimbabwe
1700       Zimbabwe
1701       Zimbabwe
1702       Zimbabwe
1703       Zimbabwe
Name: country, Length: 1704, dtype: object

In [25]:
# single column is known as series
type(df['country'])

pandas.core.series.Series

In [26]:
df['continent'].head()

0    Asia
1    Asia
2    Asia
3    Asia
4    Asia
Name: continent, dtype: object

In [27]:
df['continent'].tail()

1699    Africa
1700    Africa
1701    Africa
1702    Africa
1703    Africa
Name: continent, dtype: object

In [10]:
# multiple columns can be printed by passing a list of columns inside dataframe
df[['continent', 'country', 'population', 'life_exp']]

     continent      country  population  life_exp
0         Asia  Afghanistan     8425333    28.801
1         Asia  Afghanistan     9240934    30.332
2         Asia  Afghanistan    10267083    31.997
3         Asia  Afghanistan    11537966    34.020
4         Asia  Afghanistan    13079460    36.088
...        ...          ...         ...       ...
1699    Africa     Zimbabwe     9216418    62.351
1700    Africa     Zimbabwe    10704340    60.377
1701    Africa     Zimbabwe    11404948    46.809
1702    Africa     Zimbabwe    11926563    39.989
1703    Africa     Zimbabwe    12311143    43.487

[1704 rows x 4 columns]

By displaying multiple columns we can see a dataframe, so all dataframe methods can be applied on that

In [11]:
df[['continent', 'country', 'population', 'life_exp']].head()

  continent      country  population  life_exp
0      Asia  Afghanistan     8425333    28.801
1      Asia  Afghanistan     9240934    30.332
2      Asia  Afghanistan    10267083    31.997
3      Asia  Afghanistan    11537966    34.020
4      Asia  Afghanistan    13079460    36.088

In [31]:
# .keys() - used to print the names of the columns 
df.keys()

Index(['country', 'year', 'population', 'continent', 'life_exp', 'gdp_cap'], dtype='object')

In [32]:
# # .columns() - it is also used to print the names of the columns 
df.columns

Index(['country', 'year', 'population', 'continent', 'life_exp', 'gdp_cap'], dtype='object')

In [33]:
# .values() - used to print the values of the dataframe
df.values

array([['Afghanistan', 1952, 8425333, 'Asia', 28.801, 779.4453145],
       ['Afghanistan', 1957, 9240934, 'Asia', 30.332, 820.8530296],
       ['Afghanistan', 1962, 10267083, 'Asia', 31.997, 853.10071],
       ...,
       ['Zimbabwe', 1997, 11404948, 'Africa', 46.809, 792.4499603],
       ['Zimbabwe', 2002, 11926563, 'Africa', 39.989, 672.0386227],
       ['Zimbabwe', 2007, 12311143, 'Africa', 43.487, 469.7092981]],
      dtype=object)

In [35]:
# this way values of a single column can be printed.
# this returns an array

df['country'].values

array(['Afghanistan', 'Afghanistan', 'Afghanistan', ..., 'Zimbabwe',
       'Zimbabwe', 'Zimbabwe'], dtype=object)

In [37]:
# nunique when applied on dataframe returns the total number of unique values in each column
df.nunique()

country        142
year            12
population    1704
continent        5
life_exp      1626
gdp_cap       1704
dtype: int64

In [38]:
# nunique can be applied on a column too
df['country'].nunique()

142

In [39]:
df['gdp_cap'].nunique()

1704

In [40]:
# unique is a series method, when applied on a column returns all the unique values present in that column
df['country'].unique()

array(['Afghanistan', 'Albania', 'Algeria', 'Angola', 'Argentina',
       'Australia', 'Austria', 'Bahrain', 'Bangladesh', 'Belgium',
       'Benin', 'Bolivia', 'Bosnia and Herzegovina', 'Botswana', 'Brazil',
       'Bulgaria', 'Burkina Faso', 'Burundi', 'Cambodia', 'Cameroon',
       'Canada', 'Central African Republic', 'Chad', 'Chile', 'China',
       'Colombia', 'Comoros', 'Congo, Dem. Rep.', 'Congo, Rep.',
       'Costa Rica', "Cote d'Ivoire", 'Croatia', 'Cuba', 'Czech Republic',
       'Denmark', 'Djibouti', 'Dominican Republic', 'Ecuador', 'Egypt',
       'El Salvador', 'Equatorial Guinea', 'Eritrea', 'Ethiopia',
       'Finland', 'France', 'Gabon', 'Gambia', 'Germany', 'Ghana',
       'Greece', 'Guatemala', 'Guinea', 'Guinea-Bissau', 'Haiti',
       'Honduras', 'Hong Kong, China', 'Hungary', 'Iceland', 'India',
       'Indonesia', 'Iran', 'Iraq', 'Ireland', 'Israel', 'Italy',
       'Jamaica', 'Japan', 'Jordan', 'Kenya', 'Korea, Dem. Rep.',
       'Korea, Rep.', 'Kuwait', 'Lebanon', 'Lesotho', 'Liberia', 'Libya',
       'Madagascar', 'Malawi', 'Malaysia', 'Mali', 'Mauritania',
       'Mauritius', 'Mexico', 'Mongolia', 'Montenegro', 'Morocco',
       'Mozambique', 'Myanmar', 'Namibia', 'Nepal', 'Netherlands',
       'New Zealand', 'Nicaragua', 'Niger', 'Nigeria', 'Norway', 'Oman',
       'Pakistan', 'Panama', 'Paraguay', 'Peru', 'Philippines', 'Poland',
       'Portugal', 'Puerto Rico', 'Reunion', 'Romania', 'Rwanda',
       'Sao Tome and Principe', 'Saudi Arabia', 'Senegal', 'Serbia',
       'Sierra Leone', 'Singapore', 'Slovak Republic', 'Slovenia',
       'Somalia', 'South Africa', 'Spain', 'Sri Lanka', 'Sudan',
       'Swaziland', 'Sweden', 'Switzerland', 'Syria', 'Taiwan',
       'Tanzania', 'Thailand', 'Togo', 'Trinidad and Tobago', 'Tunisia',
       'Turkey', 'Uganda', 'United Kingdom', 'United States', 'Uruguay',
       'Venezuela', 'Vietnam', 'West Bank and Gaza', 'Yemen, Rep.',
       'Zambia', 'Zimbabwe'], dtype=object)

In [42]:
df['year'].unique()

array([1952, 1957, 1962, 1967, 1972, 1977, 1982, 1987, 1992, 1997, 2002,
       2007], dtype=int64)

In [12]:
# value_counts() - this is used to print the count of each unique value inside a column 
df['country'].value_counts()

country
Afghanistan          12
Pakistan             12
New Zealand          12
Nicaragua            12
Niger                12
                     ..
Eritrea              12
Equatorial Guinea    12
El Salvador          12
Egypt                12
Zimbabwe             12
Name: count, Length: 142, dtype: int64

In [46]:
df['continent'].value_counts()

continent
Africa      624
Asia        396
Europe      360
Americas    300
Oceania      24
Name: count, dtype: int64

In [55]:
# a series can also be printed in the following manner too -
df.country

0       Afghanistan
1       Afghanistan
2       Afghanistan
3       Afghanistan
4       Afghanistan
           ...
1699       Zimbabwe
1700       Zimbabwe
1701       Zimbabwe
1702       Zimbabwe
1703       Zimbabwe
Name: country, Length: 1704, dtype: object

But this fails when there is a space in between a column name

### Ex-

In [56]:
data = {
    'First Name':['A', 'B', 'C', 'D'],
    'Salary':[34, 12, 40, 28]
}

In [57]:
X = pd.DataFrame(data)

In [58]:
X

  First Name  Salary
0          A      34
1          B      12
2          C      40
3          D      28

In [61]:
X['Salary']

0    34
1    12
2    40
3    28
Name: Salary, dtype: int64

In [62]:
X.Salary

0    34
1    12
2    40
3    28
Name: Salary, dtype: int64

In [63]:
X['First Name']

0    A
1    B
2    C
3    D
Name: First Name, dtype: object

In [66]:
# X.First Name         # this will raise an error