In [43]:
import re
import os
import warnings
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

warnings.filterwarnings('ignore')

In [44]:
os.listdir()

['day_5_End_to_End_EDA_analysis 2.ipynb', 'scraped_data.csv']

In [45]:
df = pd.read_csv(r"scraped_data.csv")

In [46]:
df1 = df.copy()

In [47]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 342 entries, 0 to 341
Data columns (total 16 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Unnamed: 0          342 non-null    int64
 1   product_name        342 non-null    str
 2   brand               342 non-null    str
 3   rating              329 non-null    float64
 4   price               342 non-null    int64
 5   actual_price        342 non-null    int64
 6   page_number         342 non-null    int64
 7   ram_gb              342 non-null    int64
 8   storage_gb          342 non-null    int64
 9   battery_mah         342 non-null    int64
 10  camera_mp           342 non-null    str
 11  discount            287 non-null    float64
 12  rear_mp             342 non-null    float64
 13  rear_camera_count   342 non-null    int64
 14  front_mp            269 non-null    float64
 15  front_camera_count  342 non-null    int64
dtypes: float64(4), int64(9), str(3)
memory usage: 42.9 KB

In [48]:
df.columns

Index(['Unnamed: 0', 'product_name', 'brand', 'rating', 'price',
       'actual_price', 'page_number', 'ram_gb', 'storage_gb', 'battery_mah',
       'camera_mp', 'discount', 'rear_mp', 'rear_camera_count', 'front_mp',
       'front_camera_count'],
      dtype='str')

In [49]:
df.head()

,Unnamed: 0,product_name,brand,rating,price,actual_price,page_number,ram_gb,storage_gb,battery_mah,camera_mp,discount,rear_mp,rear_camera_count,front_mp,front_camera_count
0,359,"Ai+ Nova 2 (Green, 128 GB)",Ai+,3.9,14999,14999,16,6,128,6000,50MP Rear Camera | 8MP Front Camera,NaN,50.0,1,8.0,1
1,218,"Ai+ Nova 2 5G (Blue, 128 GB)",Ai+,4.0,14999,14999,10,6,128,6000,50MP Rear Camera | 8MP Front Camera,NaN,50.0,1,8.0,1
2,279,"Ai+ Nova 2 5G (Purple, 128 GB)",Ai+,4.2,13999,17499,13,4,128,6000,50MP Rear Camera | 8MP Front Camera,20.0,50.0,1,8.0,1
3,113,"Ai+ Nova 2 Neo 5G (Blue, 64 GB)",Ai+,4.3,13999,17999,5,4,64,6000,48MP Rear Camera | 8MP Front Camera,22.0,48.0,1,8.0,1
4,33,"Ai+ Nova 2 Neo 5G (Green, 128 GB)",Ai+,4.3,14499,18999,2,4,128,6000,48MP Rear Camera | 8MP Front Camera,23.0,48.0,1,8.0,1

In [50]:
df.tail()

,Unnamed: 0,product_name,brand,rating,price,actual_price,page_number,ram_gb,storage_gb,battery_mah,camera_mp,discount,rear_mp,rear_camera_count,front_mp,front_camera_count
337,757,"vivo X300 Ultra (Victory Green, 512 GB)",vivo,4.5,159999,199999,36,16,512,6600,200MP + 50MP + 200MP | 50MP Front Camera,20.0,200.0,3,50.0,1
338,510,"vivo Y11 5G (Cosmic Gold, 64 GB)",vivo,4.1,18999,39999,23,4,64,6500,13MP + 0.08MP | 5MP Front Camera,52.0,13.0,2,5.0,1
339,730,"vivo Y19s 5G (Titanium Silver, 64.0 GB)",vivo,4.3,17999,39999,34,4,64,6000,13MP + 0.08MP | 5MP Front Camera,55.0,13.0,2,5.0,1
340,862,"vivo Y31t 5G (Crimson Red, 128 GB)",vivo,5.0,26999,39999,40,4,128,7200,50MP + 2MP | 8MP Front Camera,32.0,50.0,2,8.0,1
341,654,"vivo Y51 Pro 5G (Crimson Red, 128 GB)",vivo,4.3,34999,54999,30,8,128,7200,50MP + 2MP | 8MP Front Camera,36.0,50.0,2,8.0,1

In [51]:
df.columns

Index(['Unnamed: 0', 'product_name', 'brand', 'rating', 'price',
       'actual_price', 'page_number', 'ram_gb', 'storage_gb', 'battery_mah',
       'camera_mp', 'discount', 'rear_mp', 'rear_camera_count', 'front_mp',
       'front_camera_count'],
      dtype='str')

In [52]:
df.columns = df.columns.str.lower()

In [53]:
df.columns

Index(['unnamed: 0', 'product_name', 'brand', 'rating', 'price',
       'actual_price', 'page_number', 'ram_gb', 'storage_gb', 'battery_mah',
       'camera_mp', 'discount', 'rear_mp', 'rear_camera_count', 'front_mp',
       'front_camera_count'],
      dtype='str')

In [54]:
df.product_name

0                   Ai+ Nova 2 (Green, 128 GB)
1                 Ai+ Nova 2 5G (Blue, 128 GB)
2               Ai+ Nova 2 5G (Purple, 128 GB)
3              Ai+ Nova 2 Neo 5G (Blue, 64 GB)
4            Ai+ Nova 2 Neo 5G (Green, 128 GB)
                        ...
337    vivo X300 Ultra (Victory Green, 512 GB)
338           vivo Y11 5G (Cosmic Gold, 64 GB)
339    vivo Y19s 5G (Titanium Silver, 64.0 GB)
340         vivo Y31t 5G (Crimson Red, 128 GB)
341      vivo Y51 Pro 5G (Crimson Red, 128 GB)
Name: product_name, Length: 342, dtype: str

In [55]:
print(df['product_name'].head(2))
print(type(df['product_name'].head(2)))

0      Ai+ Nova 2 (Green, 128 GB)
1    Ai+ Nova 2 5G (Blue, 128 GB)
Name: product_name, dtype: str
<class 'pandas.Series'>

In [56]:
display(df[['product_name']].head(2))
display(type(df[['product_name']].head(2)))

                   product_name
0    Ai+ Nova 2 (Green, 128 GB)
1  Ai+ Nova 2 5G (Blue, 128 GB)

pandas.DataFrame

In [57]:
display(df[['product_name']].head(2))
display((df[['product_name']].tail(2)))

                   product_name
0    Ai+ Nova 2 (Green, 128 GB)
1  Ai+ Nova 2 5G (Blue, 128 GB)

                              product_name
340     vivo Y31t 5G (Crimson Red, 128 GB)
341  vivo Y51 Pro 5G (Crimson Red, 128 GB)

In [58]:
df.columns

Index(['unnamed: 0', 'product_name', 'brand', 'rating', 'price',
       'actual_price', 'page_number', 'ram_gb', 'storage_gb', 'battery_mah',
       'camera_mp', 'discount', 'rear_mp', 'rear_camera_count', 'front_mp',
       'front_camera_count'],
      dtype='str')

In [59]:
df.rename({'product name':"product_name",'original price':'original_price'},axis=1,inplace=True)

In [60]:
df.columns

Index(['unnamed: 0', 'product_name', 'brand', 'rating', 'price',
       'actual_price', 'page_number', 'ram_gb', 'storage_gb', 'battery_mah',
       'camera_mp', 'discount', 'rear_mp', 'rear_camera_count', 'front_mp',
       'front_camera_count'],
      dtype='str')

In [61]:
df.product_name[0]

'Ai+ Nova 2 (Green, 128 GB)'

In [62]:
re.findall("[\w]+","ASUS Vivobook 14 (2025) with Office 2024 + M365 Basic*, Backlit Keyboard, Snapdragon X - (16 GB/512 GB...'")[0]

'ASUS'

In [63]:
df['brands'] = df['product_name'].apply(lambda x:re.findall(r"\w+",x)[0])

In [64]:
df.brands.value_counts()

brands
Samsung     69
realme      50
OPPO        39
REDMI       33
vivo        25
POCO        22
MOTOROLA    18
Ai          16
Infinix     11
Nothing     10
OnePlus     10
Google       9
IQOO         7
Tecno        7
BOLTT        5
LAVA         4
HMD          3
Mivi         2
Vivo         2
Name: count, dtype: int64

In [65]:
df.brands.unique()

<StringArray>
[      'Ai',    'BOLTT',   'Google',      'HMD',     'IQOO',  'Infinix',
     'LAVA', 'MOTOROLA',     'Mivi',  'Nothing',     'OPPO',  'OnePlus',
     'POCO',    'REDMI',  'Samsung',    'Tecno',     'Vivo',   'realme',
     'vivo']
Length: 19, dtype: str

In [66]:
len(df.brands.unique())

19

In [67]:
df.price

0       14999
1       14999
2       13999
3       13999
4       14499
        ...
337    159999
338     18999
339     17999
340     26999
341     34999
Name: price, Length: 342, dtype: int64

In [68]:
df['sc_price'] = df['price'].apply(lambda x:re.sub(r'[₹,]','',x)).astype('UInt32')

TypeError: expected string or bytes-like object, got 'int'

In [ ]:
df.isnull().sum()

In [ ]:
# 64 - 8 bytes- 1byte-8bits - int64 - uint64

In [ ]:
display(df.sc_price.min())
display(df.sc_price.max())

In [ ]:
df.original_price

In [ ]:
df['ogs_price'] = df['original_price'].apply(lambda x:re.sub(r'[₹,]','',x) if isinstance(x,str) else x).astype('UInt32')

In [ ]:
display(df.ogs_price.min())
display(df.ogs_price.max())

In [ ]:
df.discount[0]

In [ ]:
df.discount.unique()

In [ ]:
re.findall(r"\d+","50% off")[0]

In [ ]:
df['discount_p'] = df['discount'].apply(lambda x:re.findall(r'\d+',x)[0] if isinstance(x,str) else x).astype('UInt8')

In [ ]:
df.discount_p.unique()

In [ ]:
df['reviews']

In [ ]:
df[['rating','reviews']] = df['reviews'].str.split('&',expand=True)

In [ ]:
df['rating']

In [ ]:
re.findall(r"[0-9,]+","2,617 Ratings")

In [ ]:
df.isnull().sum()

In [ ]:
df['rating_num'] = df['rating'].apply(lambda x:re.findall(r'[0-9,]+',x)[0] if isinstance(x,str) else x).str.replace(',','').astype('UInt16')

In [ ]:
df['reviews'].value_counts()

In [ ]:
re.findall(r"[0-9,]+","2,617 Ratings")

In [ ]:
print(df.reviews.to_numpy())

In [ ]:
df['reviews'].apply(lambda x:re.findall(r'[0-9,]+',x)[0] if isinstance(x,str) else x).str.replace(',','').astype('UInt16').to_numpy()

In [ ]:
df['reviews_num'] = df['reviews'].apply(lambda x:re.findall(r'[0-9,]+',x)[0] if isinstance(x,str) else x).str.replace(',','').astype('UInt16').astype('UInt16')

In [ ]:
df['features']

In [ ]:
re.findall(r"\d+\s*GB","Intel Core Ultra 7 Processor (1st Gen)32 GB LP ed4 GB ef 8GB")

In [ ]:
df['gb_list'] = df['features'].apply(lambda x:re.findall(r"\d+\s*GB",x) if isinstance(x,str) else x)

In [ ]:
df['features'].apply(lambda x:re.findall(r"\d+\s*GB",x) if isinstance(x,str) else x)

In [ ]:
df['ram'] = df['gb_list'].apply(lambda x:x[0] if len(x)>0 else np.nan)

In [ ]:
df['rom'] = df['gb_list'].apply(lambda x:x[1] if len(x)>1 else np.nan)

In [ ]:
df.head(1)

In [ ]:
df.info()

In [ ]:
df.columns

In [ ]:
df.drop(['product_name','price','original_price','discount','discount_%','rating','reviews','features'],axis=1,inplace=True)

In [ ]:
df.columns

In [ ]:
df.drop('gb_list',axis=1,inplace=True)

In [ ]:
df.columns

# cleaning or preprocessing

In [ ]:
df.isnull().sum()

In [ ]:
df.to_csv('laptop_cleaned_scraped_data.csv',index=False)

In [ ]:
cdf = pd.read_csv("laptop_cleaned_scraped_data.csv")
cdf.head()

In [ ]:
cdf1 = cdf.copy()

In [ ]:
df[df['rom'].isnull()]

In [ ]:
df.dropna(inplace=True)

In [ ]:
df

In [ ]:
df.duplicated().sum()

In [ ]:
df[df.duplicated(keep=False)]

In [ ]:
df.drop_duplicates(keep='first',inplace=True,ignore_index=False)

In [ ]:
df.duplicated().sum()

In [ ]:
df.boxplot()

# univariate analysis

In [ ]:
df['brands'].value_counts()

# insights
### most of the times asus and hp is occured

In [ ]:
df['brands'].value_counts().plot(kind='bar')
plt.show()

In [ ]:
df['ram'].value_counts().plot(kind='bar')
plt.show()

In [ ]:
df['rom'].value_counts().plot(kind='bar')
plt.show()

In [ ]:
import seaborn as sns

In [ ]:
plt.figure(figsize=(8,5))
sns.histplot(df['sc_price'],kde=True)

plt.show()

# Bivariate analysis

In [ ]:
sns.scatterplot(x="sc_price",y='sc_price',data=df)
plt.show()

In [ ]:
sns.scatterplot(x="sc_price",y='ogs_price',data=df)
plt.show()

In [ ]:
df.columns

In [ ]:
sns.scatterplot(x="sc_price",y="ogs_price",hue='ram',data=df)
plt.show()

In [ ]:
sns.scatterplot(x="sc_price",y="ogs_price",hue='rom',data=df)
plt.show()

In [ ]:
df.select_dtypes(include='number').corr()

In [ ]:
sns.heatmap(df.select_dtypes(include='number').corr(),annot=True)
plt.show()

In [ ]:
df.describe()

In [ ]:
df.describe(include='all')

In [ ]:
sns.pairplot(df)
plt.show()

# insights

# Make Data Driven Decisions