In [1]:
import pandas as pd

In [169]:
df = pd.read_csv('Iris.csv')
df.head()

   Id  Sepal Length  Sepal Width  Petal Length  Petal Width Species
0   1           5.1          3.5           1.4          0.2  setosa
1   2           4.9          3.0           1.4          0.2  setosa
2   3           4.7          3.2           1.3          0.2  setosa
3   4           4.6          3.1           1.5          0.2  setosa
4   5           5.0          3.6           1.4          0.2  setosa

In [170]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Id            150 non-null    int64
 1   Sepal Length  149 non-null    float64
 2   Sepal Width   147 non-null    float64
 3   Petal Length  147 non-null    float64
 4   Petal Width   148 non-null    float64
 5   Species       150 non-null    object
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB

#### Setting-Resetting Index

- There are implicit indices for both rows and columns.
- Labels provided to columns are explicit index.
- If we want to set any column as an index to the dataframe, we can use set_index method.

In [171]:
# display index before setting
df.index

RangeIndex(start=0, stop=150, step=1)

In [172]:
# Set index
df.set_index('Id', inplace=True)

In [173]:
df.head()

    Sepal Length  Sepal Width  Petal Length  Petal Width Species
Id
1            5.1          3.5           1.4          0.2  setosa
2            4.9          3.0           1.4          0.2  setosa
3            4.7          3.2           1.3          0.2  setosa
4            4.6          3.1           1.5          0.2  setosa
5            5.0          3.6           1.4          0.2  setosa

In [174]:
# Here explicit index is used for both rows and columns
df.loc[2:4,'Sepal Length':'Petal Length']

    Sepal Length  Sepal Width  Petal Length
Id
2            4.9          3.0           1.4
3            4.7          3.2           1.3
4            4.6          3.1           1.5

In [175]:
df.index

Index([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,
       ...
       141, 142, 143, 144, 145, 146, 147, 148, 149, 150],
      dtype='int64', name='Id', length=150)

In [176]:
# for resetting the index back, we use reset method
df.reset_index(inplace=True)

In [177]:
df.head()

   Id  Sepal Length  Sepal Width  Petal Length  Petal Width Species
0   1           5.1          3.5           1.4          0.2  setosa
1   2           4.9          3.0           1.4          0.2  setosa
2   3           4.7          3.2           1.3          0.2  setosa
3   4           4.6          3.1           1.5          0.2  setosa
4   5           5.0          3.6           1.4          0.2  setosa

#### Renaming a column

In [178]:
df.rename({'Sepal Length':'Sepal Length (in cm)'}, axis=1, inplace=True)

In [179]:
df.head()

   Id  Sepal Length (in cm)  Sepal Width  Petal Length  Petal Width Species
0   1                   5.1          3.5           1.4          0.2  setosa
1   2                   4.9          3.0           1.4          0.2  setosa
2   3                   4.7          3.2           1.3          0.2  setosa
3   4                   4.6          3.1           1.5          0.2  setosa
4   5                   5.0          3.6           1.4          0.2  setosa

In [180]:
# Renaming multiple columns together

df.rename({'Sepal Width':'Sepal Width (in cm)', 'Petal Length':'Petal Length (in cm)', 'Petal Width':'Petal Width (in cm)'}, 
          axis=1, inplace=True)

In [181]:
df.head()

,Id,Sepal Length (in cm),Sepal Width (in cm),Petal Length (in cm),Petal Width (in cm),Species
0,1,5.1,3.5,1.4,0.2,setosa
1,2,4.9,3.0,1.4,0.2,setosa
2,3,4.7,3.2,1.3,0.2,setosa
3,4,4.6,3.1,1.5,0.2,setosa
4,5,5.0,3.6,1.4,0.2,setosa

#### Sorting Data in Pandas

In [182]:
# by default it sorts the data in ascending order
df.sort_values('Sepal Length (in cm)')

,Id,Sepal Length (in cm),Sepal Width (in cm),Petal Length (in cm),Petal Width (in cm),Species
13,14,4.3,3.0,1.1,0.1,setosa
42,43,4.4,NaN,1.3,0.2,setosa
38,39,4.4,3.0,1.3,0.2,setosa
8,9,4.4,2.9,1.4,0.2,setosa
41,42,4.5,2.3,1.3,0.3,setosa
...,...,...,...,...,...,...
117,118,7.7,3.8,6.7,2.2,virginica
118,119,7.7,2.6,6.9,2.3,virginica
122,123,7.7,2.8,6.7,2.0,virginica
131,132,7.9,3.8,6.4,2.0,virginica
130,131,NaN,2.8,6.1,1.9,virginica

In [183]:
df.sort_values('Sepal Width (in cm)')

,Id,Sepal Length (in cm),Sepal Width (in cm),Petal Length (in cm),Petal Width (in cm),Species
60,61,5.0,2.0,3.5,1.0,versicolor
119,120,6.0,2.2,5.0,1.5,virginica
68,69,6.2,2.2,4.5,1.5,versicolor
62,63,6.0,2.2,4.0,1.0,versicolor
53,54,5.5,2.3,4.0,1.3,versicolor
...,...,...,...,...,...,...
33,34,5.5,4.2,1.4,0.2,setosa
15,16,5.7,4.4,1.5,0.4,setosa
14,15,5.8,NaN,1.2,0.2,setosa
42,43,4.4,NaN,1.3,0.2,setosa
88,89,5.6,NaN,4.1,1.3,versicolor

For sorting the data in descending/decreasing order, we set ascending=False parameter

In [184]:
df.sort_values('Sepal Width (in cm)', ascending=False)

,Id,Sepal Length (in cm),Sepal Width (in cm),Petal Length (in cm),Petal Width (in cm),Species
15,16,5.7,4.4,1.5,0.4,setosa
33,34,5.5,4.2,1.4,0.2,setosa
32,33,5.2,4.1,1.5,0.1,setosa
5,6,5.4,3.9,1.7,0.4,setosa
16,17,5.4,3.9,1.3,0.4,setosa
...,...,...,...,...,...,...
119,120,6.0,2.2,5.0,1.5,virginica
60,61,5.0,2.0,3.5,1.0,versicolor
14,15,5.8,NaN,1.2,0.2,setosa
42,43,4.4,NaN,1.3,0.2,setosa
88,89,5.6,NaN,4.1,1.3,versicolor

Sorting Multiple columns together

In [185]:
df.sort_values('Sepal Length (in cm)')

,Id,Sepal Length (in cm),Sepal Width (in cm),Petal Length (in cm),Petal Width (in cm),Species
13,14,4.3,3.0,1.1,0.1,setosa
42,43,4.4,NaN,1.3,0.2,setosa
38,39,4.4,3.0,1.3,0.2,setosa
8,9,4.4,2.9,1.4,0.2,setosa
41,42,4.5,2.3,1.3,0.3,setosa
...,...,...,...,...,...,...
117,118,7.7,3.8,6.7,2.2,virginica
118,119,7.7,2.6,6.9,2.3,virginica
122,123,7.7,2.8,6.7,2.0,virginica
131,132,7.9,3.8,6.4,2.0,virginica
130,131,NaN,2.8,6.1,1.9,virginica

In [186]:
df.sort_values(['Sepal Length (in cm)','Sepal Width (in cm)'])

,Id,Sepal Length (in cm),Sepal Width (in cm),Petal Length (in cm),Petal Width (in cm),Species
13,14,4.3,3.0,1.1,0.1,setosa
8,9,4.4,2.9,1.4,0.2,setosa
38,39,4.4,3.0,1.3,0.2,setosa
42,43,4.4,NaN,1.3,0.2,setosa
41,42,4.5,2.3,1.3,0.3,setosa
...,...,...,...,...,...,...
122,123,7.7,2.8,6.7,2.0,virginica
135,136,7.7,3.0,6.1,2.3,virginica
117,118,7.7,3.8,6.7,2.2,virginica
131,132,7.9,3.8,6.4,2.0,virginica
130,131,NaN,2.8,6.1,1.9,virginica

In [187]:
# Sorting multiple columns in decreasing order
df.sort_values(['Sepal Length (in cm)','Sepal Width (in cm)'], ascending=False)

,Id,Sepal Length (in cm),Sepal Width (in cm),Petal Length (in cm),Petal Width (in cm),Species
131,132,7.9,3.8,6.4,2.0,virginica
117,118,7.7,3.8,6.7,2.2,virginica
135,136,7.7,3.0,6.1,2.3,virginica
122,123,7.7,2.8,6.7,2.0,virginica
118,119,7.7,2.6,6.9,2.3,virginica
...,...,...,...,...,...,...
38,39,4.4,3.0,1.3,0.2,setosa
8,9,4.4,2.9,1.4,0.2,setosa
42,43,4.4,NaN,1.3,0.2,setosa
13,14,4.3,3.0,1.1,0.1,setosa
130,131,NaN,2.8,6.1,1.9,virginica

In [188]:
# Sorting multiple columns in different orders
df.sort_values(['Sepal Length (in cm)', 'Sepal Width (in cm)'], ascending=[False, True])

,Id,Sepal Length (in cm),Sepal Width (in cm),Petal Length (in cm),Petal Width (in cm),Species
131,132,7.9,3.8,6.4,2.0,virginica
118,119,7.7,2.6,6.9,2.3,virginica
122,123,7.7,2.8,6.7,2.0,virginica
135,136,7.7,3.0,6.1,2.3,virginica
117,118,7.7,3.8,6.7,2.2,virginica
...,...,...,...,...,...,...
8,9,4.4,2.9,1.4,0.2,setosa
38,39,4.4,3.0,1.3,0.2,setosa
42,43,4.4,NaN,1.3,0.2,setosa
13,14,4.3,3.0,1.1,0.1,setosa
130,131,NaN,2.8,6.1,1.9,virginica

#### Aggregate Operations on Dataframe

In [189]:
# Calculating the mean
df['Sepal Length (in cm)'].mean()

5.832885906040268

In [190]:
# Calculating the median
df['Sepal Length (in cm)'].median()

5.8

In [191]:
# Calculating the mode
df['Sepal Length (in cm)'].mode()

0    5.0
Name: Sepal Length (in cm), dtype: float64

In [192]:
# Finding the max value
df['Sepal Length (in cm)'].max()

7.9

In [193]:
# Finding the min value
df['Sepal Length (in cm)'].min()

4.3

In [194]:
# Calculate the sum (total)
df['Sepal Length (in cm)'].sum()

869.0999999999999

In [195]:
# Calculate the count of rows (length of column)
df['Sepal Length (in cm)'].count()

149

In [196]:
len(df['Sepal Length (in cm)'])

150

- Count does not include NaNs
- len() consider all rows including NaNs

In [197]:
df['Petal Length (in cm)'].count()

147

In [198]:
len(df['Petal Length (in cm)'])

150

In [199]:
# counting the values of categorical column
df['Species'].count()

150

In [200]:
# Calculating Variance
df['Sepal Length (in cm)'].var()

0.6738436423000183

In [201]:
# Calculate Standard Deviation
df['Sepal Length (in cm)'].std()

0.8208797977170703

#### Correlation Between Multiple Columns

In [202]:
df.dtypes

Id                        int64
Sepal Length (in cm)    float64
Sepal Width (in cm)     float64
Petal Length (in cm)    float64
Petal Width (in cm)     float64
Species                  object
dtype: object

Correlation is calculated for numeric columns only

In [203]:
# df.corr()                        # this will raise an error

In [204]:
# df_numeric = df.drop('Species',axis=1)
# or
df_numeric = df.select_dtypes(include=['int','float'])

In [205]:
df_numeric.head(2)

,Id,Sepal Length (in cm),Sepal Width (in cm),Petal Length (in cm),Petal Width (in cm)
0,1,5.1,3.5,1.4,0.2
1,2,4.9,3.0,1.4,0.2

In [206]:
df_numeric.corr()

,Id,Sepal Length (in cm),Sepal Width (in cm),Petal Length (in cm),Petal Width (in cm)
Id,1.000000,0.712907,-0.384948,0.883204,0.901627
Sepal Length (in cm),0.712907,1.000000,-0.101564,0.871368,0.821327
Sepal Width (in cm),-0.384948,-0.101564,1.000000,-0.397289,-0.340337
Petal Length (in cm),0.883204,0.871368,-0.397289,1.000000,0.962450
Petal Width (in cm),0.901627,0.821327,-0.340337,0.962450,1.000000

In [207]:
# we can even calculate the correlation between selected columns as well
df_numeric[['Sepal Length (in cm)','Sepal Width (in cm)']].corr()

                      Sepal Length (in cm)  Sepal Width (in cm)
Sepal Length (in cm)              1.000000            -0.101564
Sepal Width (in cm)              -0.101564             1.000000

#### Item Assignment

In [208]:
df.head()

,Id,Sepal Length (in cm),Sepal Width (in cm),Petal Length (in cm),Petal Width (in cm),Species
0,1,5.1,3.5,1.4,0.2,setosa
1,2,4.9,3.0,1.4,0.2,setosa
2,3,4.7,3.2,1.3,0.2,setosa
3,4,4.6,3.1,1.5,0.2,setosa
4,5,5.0,3.6,1.4,0.2,setosa

In [216]:
# Replace any cell value of a particular column
df['Sepal Length (in cm)'][0] = 1000

In [210]:
df.head()

,Id,Sepal Length (in cm),Sepal Width (in cm),Petal Length (in cm),Petal Width (in cm),Species
0,1,1000.0,3.5,1.4,0.2,setosa
1,2,4.9,3.0,1.4,0.2,setosa
2,3,4.7,3.2,1.3,0.2,setosa
3,4,4.6,3.1,1.5,0.2,setosa
4,5,5.0,3.6,1.4,0.2,setosa

In [211]:
# df.iloc[row,col]
df.iloc[1:4,2] = 99999

In [212]:
df.head()

,Id,Sepal Length (in cm),Sepal Width (in cm),Petal Length (in cm),Petal Width (in cm),Species
0,1,1000.0,3.5,1.4,0.2,setosa
1,2,4.9,99999.0,1.4,0.2,setosa
2,3,4.7,99999.0,1.3,0.2,setosa
3,4,4.6,99999.0,1.5,0.2,setosa
4,5,5.0,3.6,1.4,0.2,setosa

In [251]:
df.loc[1:3,'Sepal Width (in cm)'] = 'unknown'

In [214]:
df.head()

,Id,Sepal Length (in cm),Sepal Width (in cm),Petal Length (in cm),Petal Width (in cm),Species
0,1,1000.0,3.5,1.4,0.2,setosa
1,2,4.9,unknown,1.4,0.2,setosa
2,3,4.7,unknown,1.3,0.2,setosa
3,4,4.6,unknown,1.5,0.2,setosa
4,5,5.0,3.6,1.4,0.2,setosa

#### Masking

In [217]:
df.head()

,Id,Sepal Length (in cm),Sepal Width (in cm),Petal Length (in cm),Petal Width (in cm),Species
0,1,1000.0,3.5,1.4,0.2,setosa
1,2,4.9,unknown,1.4,0.2,setosa
2,3,4.7,unknown,1.3,0.2,setosa
3,4,4.6,unknown,1.5,0.2,setosa
4,5,5.0,3.6,1.4,0.2,setosa

In [219]:
# Ques. Pick all rows with petal length > 2
df['Petal Length (in cm)'] > 2

0      False
1      False
2      False
3      False
4      False
       ...
145     True
146    False
147     True
148     True
149     True
Name: Petal Length (in cm), Length: 150, dtype: bool

In [220]:
# For viewing the data, we apply masking
df[df['Petal Length (in cm)'] > 2]

,Id,Sepal Length (in cm),Sepal Width (in cm),Petal Length (in cm),Petal Width (in cm),Species
50,51,7.0,3.2,4.7,1.4,versicolor
51,52,6.4,3.2,4.5,1.5,versicolor
52,53,6.9,3.1,4.9,1.5,versicolor
53,54,5.5,2.3,4.0,1.3,versicolor
54,55,6.5,2.8,4.6,1.5,versicolor
...,...,...,...,...,...,...
144,145,6.7,3.3,5.7,2.5,virginica
145,146,6.7,3.0,5.2,2.3,virginica
147,148,6.5,3.0,5.2,2.0,virginica
148,149,6.2,3.4,5.4,2.3,virginica
149,150,5.9,3.0,5.1,1.8,virginica

In [233]:
# We can even display a single column also after masking
# df['Petal Length (in cm)'][df['Petal Length (in cm)'] > 2]
# or
df[df['Petal Length (in cm)'] > 2]['Petal Length (in cm)']

50     4.7
51     4.5
52     4.9
53     4.0
54     4.6
      ...
144    5.7
145    5.2
147    5.2
148    5.4
149    5.1
Name: Petal Length (in cm), Length: 98, dtype: float64

In [243]:
# Applying Masking for multiple conditions
# Display all rows having Petal Length > 2 and < 4

mask = (df['Petal Length (in cm)'] > 2) & (df['Petal Length (in cm)'] < 4)

In [244]:
df[mask]

,Id,Sepal Length (in cm),Sepal Width (in cm),Petal Length (in cm),Petal Width (in cm),Species
57,58,4.9,2.4,3.3,1.0,versicolor
59,60,5.2,2.7,3.9,1.4,versicolor
60,61,5.0,2.0,3.5,1.0,versicolor
69,70,5.6,2.5,3.9,1.1,versicolor
79,80,5.7,2.6,3.5,1.0,versicolor
80,81,5.5,2.4,3.8,1.1,versicolor
81,82,5.5,2.4,3.7,1.0,versicolor
82,83,5.8,2.7,3.9,1.2,versicolor
93,94,5.0,2.3,3.3,1.0,versicolor
98,99,5.1,2.5,3.0,1.1,versicolor

In [250]:
# Ques. Display the row having Sepal Length as 7.0
df[df['Sepal Length (in cm)'] == 7.0]

,Id,Sepal Length (in cm),Sepal Width (in cm),Petal Length (in cm),Petal Width (in cm),Species
50,51,7.0,3.2,4.7,1.4,versicolor