In [153]:
import pandas as pd
import seaborn as sns

In [174]:
df = sns.load_dataset('tips')

In [175]:
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

#### String Methods 
- These methods makes it easier to work with string data such as cleaning, formatting and extracting information.
- String methods can be accessed using .str on Series objects.

In [172]:
df['time'].str

In [173]:
df['time'].str.upper()      # converting data into upper case

0      DINNER
1      DINNER
2      DINNER
3      DINNER
4      DINNER
        ...
239    DINNER
240    DINNER
241    DINNER
242    DINNER
243    DINNER
Name: time, Length: 244, dtype: object

In [161]:
df['day'] = df['day'].str.lower()      # converting data into lower case

In [162]:
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  sun  Dinner     2
1       10.34  1.66    Male     No  sun  Dinner     3
2       21.01  3.50    Male     No  sun  Dinner     3
3       23.68  3.31    Male     No  sun  Dinner     2
4       24.59  3.61  Female     No  sun  Dinner     4

In [163]:
df['sex'].str.len()      # printing the length of the string

0      6
1      4
2      4
3      4
4      6
      ..
239    4
240    6
241    4
242    4
243    6
Name: sex, Length: 244, dtype: int64

In [167]:
# to check whether a particular value is present in a column or not
df['day'].str.contains('mon')

0      False
1      False
2      False
3      False
4      False
       ...
239    False
240    False
241    False
242    False
243    False
Name: day, Length: 244, dtype: bool

In [166]:
df['day'].str.contains('sun')

0       True
1       True
2       True
3       True
4       True
       ...
239    False
240    False
241    False
242    False
243    False
Name: day, Length: 244, dtype: bool

In [168]:
# to display only the true values, we can apply masking
df[df['day'].str.contains('sun')]

     total_bill   tip     sex smoker  day    time  size
0         16.99  1.01  Female     No  sun  Dinner     2
1         10.34  1.66    Male     No  sun  Dinner     3
2         21.01  3.50    Male     No  sun  Dinner     3
3         23.68  3.31    Male     No  sun  Dinner     2
4         24.59  3.61  Female     No  sun  Dinner     4
..          ...   ...     ...    ...  ...     ...   ...
186       20.90  3.50  Female    Yes  sun  Dinner     3
187       30.46  2.00    Male    Yes  sun  Dinner     5
188       18.15  3.50  Female    Yes  sun  Dinner     3
189       23.10  4.00    Male    Yes  sun  Dinner     3
190       15.69  1.50    Male    Yes  sun  Dinner     2

[76 rows x 7 columns]

In [184]:
df['day'] = df['day'].str.capitalize()

In [185]:
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

#### Datatype Conversion

In [187]:
df['size'].head()

0    2
1    3
2    3
3    2
4    4
Name: size, dtype: int64

In [189]:
df['size'].astype('float').head()

0    2.0
1    3.0
2    3.0
3    2.0
4    4.0
Name: size, dtype: float64

In [190]:
df['total_bill'].astype('string')

0      16.99
1      10.34
2      21.01
3      23.68
4      24.59
       ...
239    29.03
240    27.18
241    22.67
242    17.82
243    18.78
Name: total_bill, Length: 244, dtype: string

In [268]:
# Let us create a small df with two columns
df2 = df[['total_bill','day']]

In [269]:
df2.head()

   total_bill  day
0       16.99  Sun
1       10.34  Sun
2       21.01  Sun
3       23.68  Sun
4       24.59  Sun

In [270]:
df2['total_bill'] = df2['total_bill'].astype('string')

C:\Users\Maisara Waseem\AppData\Local\Temp\ipykernel_20908\2239919503.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['total_bill'] = df2['total_bill'].astype('string')

In [271]:
df2.dtypes

total_bill    string[python]
day                   object
dtype: object

In [273]:
# let us apply split method of str
df2['total_bill'].str.split('.')

0      [16, 99]
1      [10, 34]
2      [21, 01]
3      [23, 68]
4      [24, 59]
         ...
239    [29, 03]
240    [27, 18]
241    [22, 67]
242    [17, 82]
243    [18, 78]
Name: total_bill, Length: 244, dtype: object

In [276]:
df2['rupees'] = df2['total_bill'].str.split('.').apply(lambda row : row[0])

C:\Users\Maisara Waseem\AppData\Local\Temp\ipykernel_20908\40675181.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['rupees'] = df2['total_bill'].str.split('.').apply(lambda row : row[0])

In [277]:
df2['paisa'] = df2['total_bill'].str.split('.').apply(lambda row : row[1])

C:\Users\Maisara Waseem\AppData\Local\Temp\ipykernel_20908\4003821484.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['paisa'] = df2['total_bill'].str.split('.').apply(lambda row : row[1])

In [278]:
df2.head()

  total_bill  day rupees paisa
0      16.99  Sun     16    99
1      10.34  Sun     10    34
2      21.01  Sun     21    01
3      23.68  Sun     23    68
4      24.59  Sun     24    59

#### Basic Mathematical Operations

In [203]:
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [204]:
df['size']+5

0      7
1      8
2      8
3      7
4      9
      ..
239    8
240    7
241    7
242    7
243    7
Name: size, Length: 244, dtype: int64

In [205]:
df['size']*2

0      4
1      6
2      6
3      4
4      8
      ..
239    6
240    4
241    4
242    4
243    4
Name: size, Length: 244, dtype: int64

In [88]:
df['size']-2

0      0
1      1
2      1
3      0
4      2
      ..
239    1
240    0
241    0
242    0
243    0
Name: size, Length: 244, dtype: int64

In [207]:
df['total_bill'] + 10

0      26.99
1      20.34
2      31.01
3      33.68
4      34.59
       ...
239    39.03
240    37.18
241    32.67
242    27.82
243    28.78
Name: total_bill, Length: 244, dtype: float64

Ques. Create a new column named remaining_amount that shows how much of the bill remains after the customer has paid the tip.

In [210]:
df['actual_bill'] = df['total_bill'] - df['tip']

In [211]:
df.head()

   total_bill   tip     sex smoker  day    time  size  actual_bill
0       16.99  1.01  Female     No  Sun  Dinner     2        15.98
1       10.34  1.66    Male     No  Sun  Dinner     3         8.68
2       21.01  3.50    Male     No  Sun  Dinner     3        17.51
3       23.68  3.31    Male     No  Sun  Dinner     2        20.37
4       24.59  3.61  Female     No  Sun  Dinner     4        20.98

#### Apply Method
It is a method that is used to apply custom functions to rows or columns in a dataframe.<br>
**syntax-** df[column].apply(function)

In [214]:
df['total_bill'].apply(lambda row : row+10)

0      26.99
1      20.34
2      31.01
3      33.68
4      34.59
       ...
239    39.03
240    37.18
241    32.67
242    27.82
243    28.78
Name: total_bill, Length: 244, dtype: float64

In [219]:
df['smoker'].apply(lambda row : 1 if row=='Yes' else 0)

0      0
1      0
2      0
3      0
4      0
      ..
239    0
240    1
241    1
242    0
243    0
Name: smoker, Length: 244, dtype: category
Categories (2, int64): [1, 0]

Ques. Create a new column bill_category and check if:
1. Bill < 10 - Low
2. Bill between 10–20 - Medium
3. Bill > 20 - High

In [221]:
def bill_cat(row):
    if row < 10:
        return 'Low'
    elif row > 20:
        return 'High'
    else:
        return 'Medium'

In [223]:
df['bill_category'] = df['total_bill'].apply(bill_cat)

In [224]:
df.head()

,total_bill,tip,sex,smoker,day,time,size,actual_bill,bill_category
0,16.99,1.01,Female,No,Sun,Dinner,2,15.98,Medium
1,10.34,1.66,Male,No,Sun,Dinner,3,8.68,Medium
2,21.01,3.50,Male,No,Sun,Dinner,3,17.51,High
3,23.68,3.31,Male,No,Sun,Dinner,2,20.37,High
4,24.59,3.61,Female,No,Sun,Dinner,4,20.98,High

Ques. Calculate the total bill of each row after adding a 5% service charge. Store it in a new column called final_bill.

In [226]:
# how to calculate 5% of a value
# 5/100 ----> 0.05
# x = 200
# 5% of 200 = 0.05 * 200
#           = 10

In [230]:
def service_charge(row):
    service = row * 0.05       # 5% of total bill
    final = service + row
    return final

In [232]:
df['final_bill'] = df['total_bill'].apply(service_charge)

In [233]:
df.head()

,total_bill,tip,sex,smoker,day,time,size,actual_bill,bill_category,final_bill
0,16.99,1.01,Female,No,Sun,Dinner,2,15.98,Medium,17.8395
1,10.34,1.66,Male,No,Sun,Dinner,3,8.68,Medium,10.8570
2,21.01,3.50,Male,No,Sun,Dinner,3,17.51,High,22.0605
3,23.68,3.31,Male,No,Sun,Dinner,2,20.37,High,24.8640
4,24.59,3.61,Female,No,Sun,Dinner,4,20.98,High,25.8195

Ques. Create a new column called family_visit. Classify each visit as "Family" when the group size is 4 or more, and "Regular" when the group size is less than 4.

In [235]:
def visit(row):
    if row >= 4:
        return 'Family'
    else:
        return 'Regular'

In [239]:
df['family_visit'] = df['size'].apply(visit)

In [240]:
df.head()

,total_bill,tip,sex,smoker,day,time,size,actual_bill,bill_category,final_bill,family_visit
0,16.99,1.01,Female,No,Sun,Dinner,2,15.98,Medium,17.8395,Regular
1,10.34,1.66,Male,No,Sun,Dinner,3,8.68,Medium,10.8570,Regular
2,21.01,3.50,Male,No,Sun,Dinner,3,17.51,High,22.0605,Regular
3,23.68,3.31,Male,No,Sun,Dinner,2,20.37,High,24.8640,Regular
4,24.59,3.61,Female,No,Sun,Dinner,4,20.98,High,25.8195,Family

#### Map Method
It is used to transform individual values in a Series.

Ques. Transform the gender column by replacing Male → M and Female → F

In [242]:
df['sex'] = df['sex'].map({"Male":"M", "Female":"F"})

Ques. Assign Numbers to Days (Thurs - 1, Fri - 2, Sat - 3, Sun - 4)

In [244]:
df['day_mapping'] = df['day'].map({'Thur':1, 'Fri':2, 'Sat':3, 'Sun':4})

In [245]:
df.head()

,total_bill,tip,sex,smoker,day,time,size,actual_bill,bill_category,final_bill,family_visit,day_mapping
0,16.99,1.01,F,No,Sun,Dinner,2,15.98,Medium,17.8395,Regular,4
1,10.34,1.66,M,No,Sun,Dinner,3,8.68,Medium,10.8570,Regular,4
2,21.01,3.50,M,No,Sun,Dinner,3,17.51,High,22.0605,Regular,4
3,23.68,3.31,M,No,Sun,Dinner,2,20.37,High,24.8640,Regular,4
4,24.59,3.61,F,No,Sun,Dinner,4,20.98,High,25.8195,Family,4

#### Rolling Function
- It is used to perform moving window operations on numerical data (current row and the previous n rows).
- It allows us to apply functions like mean, sum, standard deviation, etc. over a sliding window of values.

**Syntax -** df['column'].rolling(window).function()<br>
window - no. of rows to consider<br>
function - can be any function

In [253]:
df['tip'].head()

0    1.01
1    1.66
2    3.50
3    3.31
4    3.61
Name: tip, dtype: float64

In [254]:
df['tip'].rolling(2).sum()              # rolling is specific to time series data

0        NaN
1       2.67
2       5.16
3       6.81
4       6.92
       ...
239    10.59
240     7.92
241     4.00
242     3.75
243     4.75
Name: tip, Length: 244, dtype: float64

In [258]:
df['tip'].rolling(5).min()

0       NaN
1       NaN
2       NaN
3       NaN
4      1.01
       ...
239    1.00
240    1.00
241    1.17
242    1.75
243    1.75
Name: tip, Length: 244, dtype: float64

In [256]:
df['total_bill'].rolling(2).mean()

0         NaN
1      13.665
2      15.675
3      22.345
4      24.135
        ...
239    32.430
240    28.105
241    24.925
242    20.245
243    18.300
Name: total_bill, Length: 244, dtype: float64

In [259]:
df['total_bill'].rolling(4).median()

0         NaN
1         NaN
2         NaN
3      19.000
4      22.345
        ...
239    30.930
240    30.930
241    28.105
242    24.925
243    20.725
Name: total_bill, Length: 244, dtype: float64

#### Expanding
- This method is similar to rolling(), but instead of using a fixed-size moving window, it uses all the data from the beginning up to the current row.
- This is useful for cumulative calculations.

In [260]:
df['total_bill'].expanding().sum()

0        16.99
1        27.33
2        48.34
3        72.02
4        96.61
        ...
239    4741.32
240    4768.50
241    4791.17
242    4808.99
243    4827.77
Name: total_bill, Length: 244, dtype: float64

In [261]:
df['tip'].expanding().mean()

0      1.010000
1      1.335000
2      2.056667
3      2.370000
4      2.618000
         ...
239    3.011792
240    3.007593
241    3.003430
242    2.998272
243    2.998279
Name: tip, Length: 244, dtype: float64

In [267]:
df['final_bill'].expanding().min()

0      17.8395
1      10.8570
2      10.8570
3      10.8570
4      10.8570
        ...
239     3.2235
240     3.2235
241     3.2235
242     3.2235
243     3.2235
Name: final_bill, Length: 244, dtype: float64

#### Handling JSON Files
##### JSON - Javascript Object Notation
Pandas allows you to directly load JSON files into a DataFrame.

In [279]:
import json

with open('students.json', 'r') as file:
    data = json.load(file)

In [280]:
# Displaying the JSON data as a dictionary
data

[{'id': 1, 'name': 'Tom', 'age': 22, 'course': 'Data Science', 'marks': 85},
 {'id': 2,
  'name': 'Sam',
  'age': 21,
  'course': 'Machine Learning',
  'marks': 91},
 {'id': 3, 'name': 'Emma', 'age': 23, 'course': 'Python', 'marks': 78}]

If the JSON file is available online, you can fetch and parse it.

In [284]:
url = 'https://raw.githubusercontent.com/domoritz/maps/master/data/iris.json'
df = pd.read_json(url)

In [285]:
df.head()

   sepalLength  sepalWidth  petalLength  petalWidth species
0          5.1         3.5          1.4         0.2  setosa
1          4.9         3.0          1.4         0.2  setosa
2          4.7         3.2          1.3         0.2  setosa
3          4.6         3.1          1.5         0.2  setosa
4          5.0         3.6          1.4         0.2  setosa

#### Nested Data
- For nested JSON structures, you can normalize the data for flat tabular representation using json_normalize

In [286]:
from pandas import json_normalize

In [287]:
data = [
            {
                "id": 1,
                "name": "Rahul",
                "department": "IT",
                "subjects": [
                                {"subject": "Python", "marks": 90},
                                {"subject": "SQL", "marks": 85}
                            ]
            },
            {
                "id": 2,
                "name": "Aman",
                "department": "AI",
                "subjects": [
                                {"subject": "Machine Learning", "marks": 95},
                                {"subject": "Deep Learning", "marks": 92}
                            ]
            }
      ]

In [288]:
data

[{'id': 1,
  'name': 'Rahul',
  'department': 'IT',
  'subjects': [{'subject': 'Python', 'marks': 90},
   {'subject': 'SQL', 'marks': 85}]},
 {'id': 2,
  'name': 'Aman',
  'department': 'AI',
  'subjects': [{'subject': 'Machine Learning', 'marks': 95},
   {'subject': 'Deep Learning', 'marks': 92}]}]

Without json_normalize

In [289]:
df = pd.DataFrame(data)
df

   id   name department                                           subjects
0   1  Rahul         IT  [{'subject': 'Python', 'marks': 90}, {'subject...
1   2   Aman         AI  [{'subject': 'Machine Learning', 'marks': 95},...

Therefore, we use json_normalize:
- record_path: convert nested data into rows
- meta: for using parent columns

In [291]:
df = json_normalize(data, record_path='subjects', meta=['id', 'name', 'department'])

In [292]:
df

            subject  marks id   name department
0            Python     90  1  Rahul         IT
1               SQL     85  1  Rahul         IT
2  Machine Learning     95  2   Aman         AI
3     Deep Learning     92  2   Aman         AI