### Data Exploration and Understanding

In [352]:
import pandas as pd
import numpy as np

In [353]:
# Loading the Iris Dataset
df = pd.read_csv("Iris.csv")

In [354]:
df.head()

   Id  Sepal Length  Sepal Width  Petal Length  Petal Width Species
0   1           5.1          3.5           1.4          0.2  setosa
1   2           4.9          3.0           1.4          0.2  setosa
2   3           4.7          3.2           1.3          0.2  setosa
3   4           4.6          3.1           1.5          0.2  setosa
4   5           5.0          3.6           1.4          0.2  setosa

In [355]:
df.shape

(150, 6)

In [356]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Id            150 non-null    int64
 1   Sepal Length  149 non-null    float64
 2   Sepal Width   147 non-null    float64
 3   Petal Length  147 non-null    float64
 4   Petal Width   148 non-null    float64
 5   Species       150 non-null    object
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB

#### Indexing and Slicing in Pandas

##### loc/iloc methods

There are two types of indexing-
1. Implicit Index (Internal indexing)
2. Explicit Index

There is only one type of internal indexing in Python and that starts from 0.
In Pandas too, implicit index is applied by default but if we change the index it is known as explicit indexing.

In [357]:
# iloc - it is an integer location based indexing. It takes the default index even though explicit index is applied
# syntax - df.iloc[row,col] 

# Accessing the element of first row & first column
df.iloc[0,0]

1

In [358]:
# Accessing the entire first row
df.iloc[0]

Id                   1
Sepal Length       5.1
Sepal Width        3.5
Petal Length       1.4
Petal Width        0.2
Species         setosa
Name: 0, dtype: object

In [359]:
df.iloc[2,1]

4.7

In [360]:
# Use slicing to print a range of elements
df.iloc[0:5,0]

0    1
1    2
2    3
3    4
4    5
Name: Id, dtype: int64

In [361]:
df.iloc[0:5,1]

0    5.1
1    4.9
2    4.7
3    4.6
4    5.0
Name: Sepal Length, dtype: float64

In [362]:
df.iloc[0:7,5]

0    setosa
1    setosa
2    setosa
3    setosa
4    setosa
5    setosa
6    setosa
Name: Species, dtype: object

In [363]:
# Accessing the first row and multiple columns
df.iloc[0,2:5]

Sepal Width     3.5
Petal Length    1.4
Petal Width     0.2
Name: 0, dtype: object

In [364]:
df.iloc[0:2, 3:5]

   Petal Length  Petal Width
0           1.4          0.2
1           1.4          0.2

In [365]:
df.iloc[2:6,1:4]

   Sepal Length  Sepal Width  Petal Length
2           4.7          3.2           1.3
3           4.6          3.1           1.5
4           5.0          3.6           1.4
5           5.4          3.9           1.7

In [366]:
# List of indices can also be used to display random rows and columns
df.iloc[[0,10,54,7,28]]

    Id  Sepal Length  Sepal Width  Petal Length  Petal Width     Species
0    1           5.1          3.5           1.4          0.2      setosa
10  11           5.4          3.7           NaN          0.2      setosa
54  55           6.5          2.8           4.6          1.5  versicolor
7    8           5.0          3.4           1.5          0.2      setosa
28  29           5.2          3.4           1.4          0.2      setosa

In [367]:
# df.iloc[row, column]
df.iloc[[0,100,25,65],[2,5,1]]

     Sepal Width     Species  Sepal Length
0            3.5      setosa           5.1
100          3.3   virginica           6.3
25           3.0      setosa           5.0
65           3.1  versicolor           6.7

In [368]:
df.iloc[[0,6,9,3],[0,5,3]]

   Id Species  Petal Length
0   1  setosa           1.4
6   7  setosa           1.4
9  10  setosa           1.5
3   4  setosa           1.5

In [369]:
# loc - it is a label-based indexing. It uses rows and columns based on the labels provided
# syntax - df.loc[row,col]

# Accessing first row
df.loc[0]

Id                   1
Sepal Length       5.1
Sepal Width        3.5
Petal Length       1.4
Petal Width        0.2
Species         setosa
Name: 0, dtype: object

In [370]:
# Accessing last row
df.loc[149]

Id                    150
Sepal Length          5.9
Sepal Width           3.0
Petal Length          5.1
Petal Width           1.8
Species         virginica
Name: 149, dtype: object

In [371]:
# Accessing specific Column of a specific row
df.loc[0,"Species"]

'setosa'

In [372]:
df.loc[1,"Sepal Length"]

4.9

In [373]:
df.loc[4,'Sepal Width']

3.6

In [374]:
# Accessing multiple rows of a single column using list of indices
df.loc[[149,23,0,74], "Species"]

149     virginica
23         setosa
0          setosa
74     versicolor
Name: Species, dtype: object

In [375]:
df.loc[[149,23,0,74], "Sepal Length"]

149    5.9
23     5.1
0      5.1
74     6.4
Name: Sepal Length, dtype: float64

In [376]:
# here too list of indices can also be passed to display random rows and columns
df.loc[[100, 60, 12, 35],['Species', 'Sepal Length', 'Petal Length']]

        Species  Sepal Length  Petal Length
100   virginica           6.3           6.0
60   versicolor           5.0           3.5
12       setosa           4.8           1.4
35       setosa           5.0           1.2

In [377]:
df.loc[0:5, 'Petal Length':'Species']

   Petal Length  Petal Width Species
0           1.4          0.2  setosa
1           1.4          0.2  setosa
2           1.3          0.2  setosa
3           1.5          0.2  setosa
4           1.4          0.2  setosa
5           1.7          0.4  setosa

#### Missing Value Detection using Pandas
- A missing value signifies an empty cell.
- Missing values are detected using isnull() or isna() methods

In [378]:
df.isnull()

        Id  Sepal Length  Sepal Width  Petal Length  Petal Width  Species
0    False         False        False         False        False    False
1    False         False        False         False        False    False
2    False         False        False         False        False    False
3    False         False        False         False        False    False
4    False         False        False         False        False    False
..     ...           ...          ...           ...          ...      ...
145  False         False        False         False        False    False
146  False         False        False          True        False    False
147  False         False        False         False        False    False
148  False         False        False         False        False    False
149  False         False        False         False        False    False

[150 rows x 6 columns]

In [379]:
df.isna()

        Id  Sepal Length  Sepal Width  Petal Length  Petal Width  Species
0    False         False        False         False        False    False
1    False         False        False         False        False    False
2    False         False        False         False        False    False
3    False         False        False         False        False    False
4    False         False        False         False        False    False
..     ...           ...          ...           ...          ...      ...
145  False         False        False         False        False    False
146  False         False        False          True        False    False
147  False         False        False         False        False    False
148  False         False        False         False        False    False
149  False         False        False         False        False    False

[150 rows x 6 columns]

In [380]:
# Verifying existance of Null values column wise
df.isnull().any()

Id              False
Sepal Length     True
Sepal Width      True
Petal Length     True
Petal Width      True
Species         False
dtype: bool

In [381]:
# column wise count of null values
df.isnull().sum()

Id              0
Sepal Length    1
Sepal Width     3
Petal Length    3
Petal Width     2
Species         0
dtype: int64

As we can see that Sepal Length column has a missing, let us apply masking to print the row with missing value

In [382]:
df["Sepal Length"].isna().sum()

1

In [383]:
df[df["Sepal Length"].isna() == True]           # this is masking

      Id  Sepal Length  Sepal Width  Petal Length  Petal Width    Species
130  131           NaN          2.8           6.1          1.9  virginica

Similarly null values can be checked for other columns as well

In [384]:
df[df["Sepal Width"].isna() == True]

    Id  Sepal Length  Sepal Width  Petal Length  Petal Width     Species
14  15           5.8          NaN           1.2          0.2      setosa
42  43           4.4          NaN           1.3          0.2      setosa
88  89           5.6          NaN           4.1          1.3  versicolor

In [385]:
df[df['Petal Length'].isna() == True]

      Id  Sepal Length  Sepal Width  Petal Length  Petal Width     Species
10    11           5.4          3.7           NaN          0.2      setosa
64    65           5.6          2.9           NaN          1.3  versicolor
146  147           6.3          2.5           NaN          1.9   virginica

**Removing nulls using dropna()**

In [386]:
df.dropna()

      Id  Sepal Length  Sepal Width  Petal Length  Petal Width    Species
0      1           5.1          3.5           1.4          0.2     setosa
1      2           4.9          3.0           1.4          0.2     setosa
2      3           4.7          3.2           1.3          0.2     setosa
3      4           4.6          3.1           1.5          0.2     setosa
4      5           5.0          3.6           1.4          0.2     setosa
..   ...           ...          ...           ...          ...        ...
144  145           6.7          3.3           5.7          2.5  virginica
145  146           6.7          3.0           5.2          2.3  virginica
147  148           6.5          3.0           5.2          2.0  virginica
148  149           6.2          3.4           5.4          2.3  virginica
149  150           5.9          3.0           5.1          1.8  virginica

[141 rows x 6 columns]

In [387]:
df.isna().sum()

Id              0
Sepal Length    1
Sepal Width     3
Petal Length    3
Petal Width     2
Species         0
dtype: int64

Changes are not observed in the original dataframe. Hence we use inplace=True for making the permanent change in the original dataset

In [388]:
# this drops all the NaNs from original dataframe
df.dropna(inplace=True)

In [389]:
df.isna().sum()

Id              0
Sepal Length    0
Sepal Width     0
Petal Length    0
Petal Width     0
Species         0
dtype: int64

In [390]:
df.shape

(141, 6)

**But what is the problem with deleting rows/columns?**
- loss of valuable data<br>
So instead of dropping, it is better to fill the missing values with some data using **fillna()** method.

#### Accessing a sample dataset from main dataframe
df.sample() - It select n rows randomly

In [391]:
df.sample(5)

    Id  Sepal Length  Sepal Width  Petal Length  Petal Width     Species
65  66           6.7          3.1           4.4          1.4  versicolor
17  18           5.1          3.5           1.4          0.3      setosa
63  64           6.1          2.9           4.7          1.4  versicolor
59  60           5.2          2.7           3.9          1.4  versicolor
18  19           5.7          3.8           1.7          0.3      setosa

In [392]:
df.sample(10)

      Id  Sepal Length  Sepal Width  Petal Length  Petal Width     Species
147  148           6.5          3.0           5.2          2.0   virginica
140  141           6.7          3.1           5.6          2.4   virginica
13    14           4.3          3.0           1.1          0.1      setosa
68    69           6.2          2.2           4.5          1.5  versicolor
144  145           6.7          3.3           5.7          2.5   virginica
1      2           4.9          3.0           1.4          0.2      setosa
83    84           6.0          2.7           5.1          1.6  versicolor
47    48           4.6          3.2           1.4          0.2      setosa
40    41           5.0          3.5           1.3          0.3      setosa
118  119           7.7          2.6           6.9          2.3   virginica

**Using random_state for reproducibility**

In [393]:
df.sample(5, random_state=42)

      Id  Sepal Length  Sepal Width  Petal Length  Petal Width     Species
73    74           6.1          2.8           4.7          1.2  versicolor
114  115           5.8          2.8           5.1          2.4   virginica
33    34           5.5          4.2           1.4          0.2      setosa
54    55           6.5          2.8           4.6          1.5  versicolor
101  102           5.8          2.7           5.1          1.9   virginica

In [394]:
df.sample(10, random_state=42)

      Id  Sepal Length  Sepal Width  Petal Length  Petal Width     Species
73    74           6.1          2.8           4.7          1.2  versicolor
114  115           5.8          2.8           5.1          2.4   virginica
33    34           5.5          4.2           1.4          0.2      setosa
54    55           6.5          2.8           4.6          1.5  versicolor
101  102           5.8          2.7           5.1          1.9   virginica
145  146           6.7          3.0           5.2          2.3   virginica
87    88           6.3          2.3           4.4          1.3  versicolor
120  121           6.9          3.2           5.7          2.3   virginica
141  142           6.9          3.1           5.1          2.3   virginica
13    14           4.3          3.0           1.1          0.1      setosa

#### Displaying the axes of the dataframe

In [395]:
df.axes

[Index([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,
        ...
        138, 139, 140, 141, 143, 144, 145, 147, 148, 149],
       dtype='int64', length=141),
 Index(['Id', 'Sepal Length', 'Sepal Width', 'Petal Length', 'Petal Width',
        'Species'],
       dtype='object')]

In [396]:
# accessing axes separately
r,c = df.axes

In [397]:
r

Index([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,
       ...
       138, 139, 140, 141, 143, 144, 145, 147, 148, 149],
      dtype='int64', length=141)

In [398]:
c

Index(['Id', 'Sepal Length', 'Sepal Width', 'Petal Length', 'Petal Width',
       'Species'],
      dtype='object')

Also, in pandas
1. axis = 1 means columns
2. axis = 0 means rows

#### Dropping rows and columns

In [399]:
df.head()

   Id  Sepal Length  Sepal Width  Petal Length  Petal Width Species
0   1           5.1          3.5           1.4          0.2  setosa
1   2           4.9          3.0           1.4          0.2  setosa
2   3           4.7          3.2           1.3          0.2  setosa
3   4           4.6          3.1           1.5          0.2  setosa
4   5           5.0          3.6           1.4          0.2  setosa

In [400]:
df.drop(0)           # by default drop method drops row only

      Id  Sepal Length  Sepal Width  Petal Length  Petal Width    Species
1      2           4.9          3.0           1.4          0.2     setosa
2      3           4.7          3.2           1.3          0.2     setosa
3      4           4.6          3.1           1.5          0.2     setosa
4      5           5.0          3.6           1.4          0.2     setosa
5      6           5.4          3.9           1.7          0.4     setosa
..   ...           ...          ...           ...          ...        ...
144  145           6.7          3.3           5.7          2.5  virginica
145  146           6.7          3.0           5.2          2.3  virginica
147  148           6.5          3.0           5.2          2.0  virginica
148  149           6.2          3.4           5.4          2.3  virginica
149  150           5.9          3.0           5.1          1.8  virginica

[140 rows x 6 columns]

In [401]:
df.drop(2)

      Id  Sepal Length  Sepal Width  Petal Length  Petal Width    Species
0      1           5.1          3.5           1.4          0.2     setosa
1      2           4.9          3.0           1.4          0.2     setosa
3      4           4.6          3.1           1.5          0.2     setosa
4      5           5.0          3.6           1.4          0.2     setosa
5      6           5.4          3.9           1.7          0.4     setosa
..   ...           ...          ...           ...          ...        ...
144  145           6.7          3.3           5.7          2.5  virginica
145  146           6.7          3.0           5.2          2.3  virginica
147  148           6.5          3.0           5.2          2.0  virginica
148  149           6.2          3.4           5.4          2.3  virginica
149  150           5.9          3.0           5.1          1.8  virginica

[140 rows x 6 columns]

In [402]:
# we can even drop the row by providing the index
df.drop(1, axis=0)

      Id  Sepal Length  Sepal Width  Petal Length  Petal Width    Species
0      1           5.1          3.5           1.4          0.2     setosa
2      3           4.7          3.2           1.3          0.2     setosa
3      4           4.6          3.1           1.5          0.2     setosa
4      5           5.0          3.6           1.4          0.2     setosa
5      6           5.4          3.9           1.7          0.4     setosa
..   ...           ...          ...           ...          ...        ...
144  145           6.7          3.3           5.7          2.5  virginica
145  146           6.7          3.0           5.2          2.3  virginica
147  148           6.5          3.0           5.2          2.0  virginica
148  149           6.2          3.4           5.4          2.3  virginica
149  150           5.9          3.0           5.1          1.8  virginica

[140 rows x 6 columns]

For dropping columns, we have to mention the axis

In [403]:
df.drop('Id', axis=1)

     Sepal Length  Sepal Width  Petal Length  Petal Width    Species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
144           6.7          3.3           5.7          2.5  virginica
145           6.7          3.0           5.2          2.3  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[141 rows x 5 columns]

For dropping multiple rows and columns

In [404]:
# Drop multiple rows
df.drop([0,2,4,12], axis=0).head(10)

    Id  Sepal Length  Sepal Width  Petal Length  Petal Width Species
1    2           4.9          3.0           1.4          0.2  setosa
3    4           4.6          3.1           1.5          0.2  setosa
5    6           5.4          3.9           1.7          0.4  setosa
6    7           4.6          3.4           1.4          0.3  setosa
7    8           5.0          3.4           1.5          0.2  setosa
8    9           4.4          2.9           1.4          0.2  setosa
9   10           4.9          3.1           1.5          0.1  setosa
11  12           4.8          3.4           1.6          0.2  setosa
13  14           4.3          3.0           1.1          0.1  setosa
15  16           5.7          4.4           1.5          0.4  setosa

In [405]:
# Drop multiple columns
df.drop(['Id', 'Sepal Width'], axis=1)

     Sepal Length  Petal Length  Petal Width    Species
0             5.1           1.4          0.2     setosa
1             4.9           1.4          0.2     setosa
2             4.7           1.3          0.2     setosa
3             4.6           1.5          0.2     setosa
4             5.0           1.4          0.2     setosa
..            ...           ...          ...        ...
144           6.7           5.7          2.5  virginica
145           6.7           5.2          2.3  virginica
147           6.5           5.2          2.0  virginica
148           6.2           5.4          2.3  virginica
149           5.9           5.1          1.8  virginica

[141 rows x 4 columns]

- The above changes are done temporarily.
- For making permanent changes, we apply inplace=True

Let us create a sample dataset of 6 rows and apply drop method

In [406]:
dummy_data = df.iloc[0:7,:]

In [407]:
dummy_data

   Id  Sepal Length  Sepal Width  Petal Length  Petal Width Species
0   1           5.1          3.5           1.4          0.2  setosa
1   2           4.9          3.0           1.4          0.2  setosa
2   3           4.7          3.2           1.3          0.2  setosa
3   4           4.6          3.1           1.5          0.2  setosa
4   5           5.0          3.6           1.4          0.2  setosa
5   6           5.4          3.9           1.7          0.4  setosa
6   7           4.6          3.4           1.4          0.3  setosa

In [408]:
dummy_data.drop([2,5], inplace=True)           # axis=0 here is optional

C:\Users\Maisara Waseem\AppData\Local\Temp\ipykernel_13236\1211374220.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dummy_data.drop([2,5], inplace=True)           # axis=0 here is optional

In [409]:
dummy_data

   Id  Sepal Length  Sepal Width  Petal Length  Petal Width Species
0   1           5.1          3.5           1.4          0.2  setosa
1   2           4.9          3.0           1.4          0.2  setosa
3   4           4.6          3.1           1.5          0.2  setosa
4   5           5.0          3.6           1.4          0.2  setosa
6   7           4.6          3.4           1.4          0.3  setosa

In [410]:
# let's drop columns too from the dummy data
dummy_data.drop(['Id', 'Petal Length', 'Species'], axis=1, inplace=True)

C:\Users\Maisara Waseem\AppData\Local\Temp\ipykernel_13236\3183862355.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dummy_data.drop(['Id', 'Petal Length', 'Species'], axis=1, inplace=True)

In [411]:
dummy_data

   Sepal Length  Sepal Width  Petal Width
0           5.1          3.5          0.2
1           4.9          3.0          0.2
3           4.6          3.1          0.2
4           5.0          3.6          0.2
6           4.6          3.4          0.3

#### Checking for the datatypes & selecting specific datatypes

In [412]:
df.dtypes

Id                int64
Sepal Length    float64
Sepal Width     float64
Petal Length    float64
Petal Width     float64
Species          object
dtype: object

Selecting columns of specific datatype

In [413]:
df.select_dtypes(include='int').head()

   Id
0   1
1   2
2   3
3   4
4   5

Similarly we can select columns with other data types

In [414]:
df.select_dtypes(include='float').head()

   Sepal Length  Sepal Width  Petal Length  Petal Width
0           5.1          3.5           1.4          0.2
1           4.9          3.0           1.4          0.2
2           4.7          3.2           1.3          0.2
3           4.6          3.1           1.5          0.2
4           5.0          3.6           1.4          0.2

In [415]:
df.select_dtypes(include='object').head()

  Species
0  setosa
1  setosa
2  setosa
3  setosa
4  setosa

We can also select multiple data types as well

In [416]:
df.select_dtypes(include=['int','object']).head()

   Id Species
0   1  setosa
1   2  setosa
2   3  setosa
3   4  setosa
4   5  setosa

##### df.empty - to check whether data exists in data frame or not

In [417]:
df.empty

False

##### df.ndim - to check the dimensionality of the data

In [418]:
df.ndim

2

##### df.values - to convert dataframe into numpy array

In [419]:
df.values

array([[1, 5.1, 3.5, 1.4, 0.2, 'setosa'],
       [2, 4.9, 3.0, 1.4, 0.2, 'setosa'],
       [3, 4.7, 3.2, 1.3, 0.2, 'setosa'],
       [4, 4.6, 3.1, 1.5, 0.2, 'setosa'],
       [5, 5.0, 3.6, 1.4, 0.2, 'setosa'],
       [6, 5.4, 3.9, 1.7, 0.4, 'setosa'],
       [7, 4.6, 3.4, 1.4, 0.3, 'setosa'],
       [8, 5.0, 3.4, 1.5, 0.2, 'setosa'],
       [9, 4.4, 2.9, 1.4, 0.2, 'setosa'],
       [10, 4.9, 3.1, 1.5, 0.1, 'setosa'],
       [12, 4.8, 3.4, 1.6, 0.2, 'setosa'],
       [13, 4.8, 3.0, 1.4, 0.1, 'setosa'],
       [14, 4.3, 3.0, 1.1, 0.1, 'setosa'],
       [16, 5.7, 4.4, 1.5, 0.4, 'setosa'],
       [17, 5.4, 3.9, 1.3, 0.4, 'setosa'],
       [18, 5.1, 3.5, 1.4, 0.3, 'setosa'],
       [19, 5.7, 3.8, 1.7, 0.3, 'setosa'],
       [20, 5.1, 3.8, 1.5, 0.3, 'setosa'],
       [21, 5.4, 3.4, 1.7, 0.2, 'setosa'],
       [22, 5.1, 3.7, 1.5, 0.4, 'setosa'],
       [23, 4.6, 3.6, 1.0, 0.2, 'setosa'],
       [24, 5.1, 3.3, 1.7, 0.5, 'setosa'],
       [25, 4.8, 3.4, 1.9, 0.2, 'setosa'],
       [26, 5.0, 3.0, 1.6, 0.2, 'setosa'],
       [27, 5.0, 3.4, 1.6, 0.4, 'setosa'],
       [28, 5.2, 3.5, 1.5, 0.2, 'setosa'],
       [29, 5.2, 3.4, 1.4, 0.2, 'setosa'],
       [30, 4.7, 3.2, 1.6, 0.2, 'setosa'],
       [31, 4.8, 3.1, 1.6, 0.2, 'setosa'],
       [32, 5.4, 3.4, 1.5, 0.4, 'setosa'],
       [33, 5.2, 4.1, 1.5, 0.1, 'setosa'],
       [34, 5.5, 4.2, 1.4, 0.2, 'setosa'],
       [35, 4.9, 3.1, 1.5, 0.1, 'setosa'],
       [36, 5.0, 3.2, 1.2, 0.2, 'setosa'],
       [37, 5.5, 3.5, 1.3, 0.2, 'setosa'],
       [38, 4.9, 3.1, 1.5, 0.1, 'setosa'],
       [39, 4.4, 3.0, 1.3, 0.2, 'setosa'],
       [40, 5.1, 3.4, 1.5, 0.2, 'setosa'],
       [41, 5.0, 3.5, 1.3, 0.3, 'setosa'],
       [42, 4.5, 2.3, 1.3, 0.3, 'setosa'],
       [44, 5.0, 3.5, 1.6, 0.6, 'setosa'],
       [45, 5.1, 3.8, 1.9, 0.4, 'setosa'],
       [46, 4.8, 3.0, 1.4, 0.3, 'setosa'],
       [47, 5.1, 3.8, 1.6, 0.2, 'setosa'],
       [48, 4.6, 3.2, 1.4, 0.2, 'setosa'],
       [49, 5.3, 3.7, 1.5, 0.2, 'setosa'],
       [50, 5.0, 3.3, 1.4, 0.2, 'setosa'],
       [51, 7.0, 3.2, 4.7, 1.4, 'versicolor'],
       [52, 6.4, 3.2, 4.5, 1.5, 'versicolor'],
       [53, 6.9, 3.1, 4.9, 1.5, 'versicolor'],
       [54, 5.5, 2.3, 4.0, 1.3, 'versicolor'],
       [55, 6.5, 2.8, 4.6, 1.5, 'versicolor'],
       [56, 5.7, 2.8, 4.5, 1.3, 'versicolor'],
       [57, 6.3, 3.3, 4.7, 1.6, 'versicolor'],
       [58, 4.9, 2.4, 3.3, 1.0, 'versicolor'],
       [59, 6.6, 2.9, 4.6, 1.3, 'versicolor'],
       [60, 5.2, 2.7, 3.9, 1.4, 'versicolor'],
       [61, 5.0, 2.0, 3.5, 1.0, 'versicolor'],
       [63, 6.0, 2.2, 4.0, 1.0, 'versicolor'],
       [64, 6.1, 2.9, 4.7, 1.4, 'versicolor'],
       [66, 6.7, 3.1, 4.4, 1.4, 'versicolor'],
       [67, 5.6, 3.0, 4.5, 1.5, 'versicolor'],
       [68, 5.8, 2.7, 4.1, 1.0, 'versicolor'],
       [69, 6.2, 2.2, 4.5, 1.5, 'versicolor'],
       [70, 5.6, 2.5, 3.9, 1.1, 'versicolor'],
       [71, 5.9, 3.2, 4.8, 1.8, 'versicolor'],
       [72, 6.1, 2.8, 4.0, 1.3, 'versicolor'],
       [73, 6.3, 2.5, 4.9, 1.5, 'versicolor'],
       [74, 6.1, 2.8, 4.7, 1.2, 'versicolor'],
       [75, 6.4, 2.9, 4.3, 1.3, 'versicolor'],
       [76, 6.6, 3.0, 4.4, 1.4, 'versicolor'],
       [77, 6.8, 2.8, 4.8, 1.4, 'versicolor'],
       [78, 6.7, 3.0, 5.0, 1.7, 'versicolor'],
       [79, 6.0, 2.9, 4.5, 1.5, 'versicolor'],
       [80, 5.7, 2.6, 3.5, 1.0, 'versicolor'],
       [81, 5.5, 2.4, 3.8, 1.1, 'versicolor'],
       [82, 5.5, 2.4, 3.7, 1.0, 'versicolor'],
       [83, 5.8, 2.7, 3.9, 1.2, 'versicolor'],
       [84, 6.0, 2.7, 5.1, 1.6, 'versicolor'],
       [85, 5.4, 3.0, 4.5, 1.5, 'versicolor'],
       [86, 6.0, 3.4, 4.5, 1.6, 'versicolor'],
       [87, 6.7, 3.1, 4.7, 1.5, 'versicolor'],
       [88, 6.3, 2.3, 4.4, 1.3, 'versicolor'],
       [90, 5.5, 2.5, 4.0, 1.3, 'versicolor'],
       [91, 5.5, 2.6, 4.4, 1.2, 'versicolor'],
       [92, 6.1, 3.0, 4.6, 1.4, 'versicolor'],
       [93, 5.8, 2.6, 4.0, 1.2, 'versicolor'],
       [94, 5.0, 2.3, 3.3, 1.0, 'versicolor'],
       [95, 5.6, 2.7, 4.2, 1.3, 'versicolor'],
       [96, 5.7, 3.0, 4.2, 1.2, 'versicolor'],
       [97, 5.7, 2.9, 4.2, 1.3, 'versicolor'],
       [98, 6.2, 2.9, 4.3, 1.3, 'versicolor'],
       [99, 5.1, 2.5, 3.0, 1.1, 'versicolor'],
       [100, 5.7, 2.8, 4.1, 1.3, 'versicolor'],
       [101, 6.3, 3.3, 6.0, 2.5, 'virginica'],
       [102, 5.8, 2.7, 5.1, 1.9, 'virginica'],
       [103, 7.1, 3.0, 5.9, 2.1, 'virginica'],
       [104, 6.3, 2.9, 5.6, 1.8, 'virginica'],
       [105, 6.5, 3.0, 5.8, 2.2, 'virginica'],
       [106, 7.6, 3.0, 6.6, 2.1, 'virginica'],
       [107, 4.9, 2.5, 4.5, 1.7, 'virginica'],
       [108, 7.3, 2.9, 6.3, 1.8, 'virginica'],
       [109, 6.7, 2.5, 5.8, 1.8, 'virginica'],
       [110, 7.2, 3.6, 6.1, 2.5, 'virginica'],
       [111, 6.5, 3.2, 5.1, 2.0, 'virginica'],
       [112, 6.4, 2.7, 5.3, 1.9, 'virginica'],
       [113, 6.8, 3.0, 5.5, 2.1, 'virginica'],
       [114, 5.7, 2.5, 5.0, 2.0, 'virginica'],
       [115, 5.8, 2.8, 5.1, 2.4, 'virginica'],
       [116, 6.4, 3.2, 5.3, 2.3, 'virginica'],
       [117, 6.5, 3.0, 5.5, 1.8, 'virginica'],
       [118, 7.7, 3.8, 6.7, 2.2, 'virginica'],
       [119, 7.7, 2.6, 6.9, 2.3, 'virginica'],
       [120, 6.0, 2.2, 5.0, 1.5, 'virginica'],
       [121, 6.9, 3.2, 5.7, 2.3, 'virginica'],
       [122, 5.6, 2.8, 4.9, 2.0, 'virginica'],
       [123, 7.7, 2.8, 6.7, 2.0, 'virginica'],
       [124, 6.3, 2.7, 4.9, 1.8, 'virginica'],
       [125, 6.7, 3.3, 5.7, 2.1, 'virginica'],
       [126, 7.2, 3.2, 6.0, 1.8, 'virginica'],
       [127, 6.2, 2.8, 4.8, 1.8, 'virginica'],
       [128, 6.1, 3.0, 4.9, 1.8, 'virginica'],
       [129, 6.4, 2.8, 5.6, 2.1, 'virginica'],
       [130, 7.2, 3.0, 5.8, 1.6, 'virginica'],
       [132, 7.9, 3.8, 6.4, 2.0, 'virginica'],
       [133, 6.4, 2.8, 5.6, 2.2, 'virginica'],
       [134, 6.3, 2.8, 5.1, 1.5, 'virginica'],
       [135, 6.1, 2.6, 5.6, 1.4, 'virginica'],
       [136, 7.7, 3.0, 6.1, 2.3, 'virginica'],
       [137, 6.3, 3.4, 5.6, 2.4, 'virginica'],
       [138, 6.4, 3.1, 5.5, 1.8, 'virginica'],
       [139, 6.0, 3.0, 4.8, 1.8, 'virginica'],
       [140, 6.9, 3.1, 5.4, 2.1, 'virginica'],
       [141, 6.7, 3.1, 5.6, 2.4, 'virginica'],
       [142, 6.9, 3.1, 5.1, 2.3, 'virginica'],
       [144, 6.8, 3.2, 5.9, 2.3, 'virginica'],
       [145, 6.7, 3.3, 5.7, 2.5, 'virginica'],
       [146, 6.7, 3.0, 5.2, 2.3, 'virginica'],
       [148, 6.5, 3.0, 5.2, 2.0, 'virginica'],
       [149, 6.2, 3.4, 5.4, 2.3, 'virginica'],
       [150, 5.9, 3.0, 5.1, 1.8, 'virginica']], dtype=object)

In [420]:
df['Petal Length'].values

array([1.4, 1.4, 1.3, 1.5, 1.4, 1.7, 1.4, 1.5, 1.4, 1.5, 1.6, 1.4, 1.1,
       1.5, 1.3, 1.4, 1.7, 1.5, 1.7, 1.5, 1. , 1.7, 1.9, 1.6, 1.6, 1.5,
       1.4, 1.6, 1.6, 1.5, 1.5, 1.4, 1.5, 1.2, 1.3, 1.5, 1.3, 1.5, 1.3,
       1.3, 1.6, 1.9, 1.4, 1.6, 1.4, 1.5, 1.4, 4.7, 4.5, 4.9, 4. , 4.6,
       4.5, 4.7, 3.3, 4.6, 3.9, 3.5, 4. , 4.7, 4.4, 4.5, 4.1, 4.5, 3.9,
       4.8, 4. , 4.9, 4.7, 4.3, 4.4, 4.8, 5. , 4.5, 3.5, 3.8, 3.7, 3.9,
       5.1, 4.5, 4.5, 4.7, 4.4, 4. , 4.4, 4.6, 4. , 3.3, 4.2, 4.2, 4.2,
       4.3, 3. , 4.1, 6. , 5.1, 5.9, 5.6, 5.8, 6.6, 4.5, 6.3, 5.8, 6.1,
       5.1, 5.3, 5.5, 5. , 5.1, 5.3, 5.5, 6.7, 6.9, 5. , 5.7, 4.9, 6.7,
       4.9, 5.7, 6. , 4.8, 4.9, 5.6, 5.8, 6.4, 5.6, 5.1, 5.6, 6.1, 5.6,
       5.5, 4.8, 5.4, 5.6, 5.1, 5.9, 5.7, 5.2, 5.2, 5.4, 5.1])

In [421]:
df['Species'].values

array(['setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'virginica', 'virginica', 'virginica',
       'virginica', 'virginica', 'virginica', 'virginica', 'virginica',
       'virginica', 'virginica', 'virginica', 'virginica', 'virginica',
       'virginica', 'virginica', 'virginica', 'virginica', 'virginica',
       'virginica', 'virginica', 'virginica', 'virginica', 'virginica',
       'virginica', 'virginica', 'virginica', 'virginica', 'virginica',
       'virginica', 'virginica', 'virginica', 'virginica', 'virginica',
       'virginica', 'virginica', 'virginica', 'virginica', 'virginica',
       'virginica', 'virginica', 'virginica', 'virginica', 'virginica',
       'virginica', 'virginica', 'virginica', 'virginica'], dtype=object)

##### Transposing a dataframe - changing rows into columns & vice versa

In [422]:
df.T

,0,1,2,3,4,5,6,7,8,9,...,138,139,140,141,143,144,145,147,148,149
Id,1,2,3,4,5,6,7,8,9,10,...,139,140,141,142,144,145,146,148,149,150
Sepal Length,5.1,4.9,4.7,4.6,5.0,5.4,4.6,5.0,4.4,4.9,...,6.0,6.9,6.7,6.9,6.8,6.7,6.7,6.5,6.2,5.9
Sepal Width,3.5,3.0,3.2,3.1,3.6,3.9,3.4,3.4,2.9,3.1,...,3.0,3.1,3.1,3.1,3.2,3.3,3.0,3.0,3.4,3.0
Petal Length,1.4,1.4,1.3,1.5,1.4,1.7,1.4,1.5,1.4,1.5,...,4.8,5.4,5.6,5.1,5.9,5.7,5.2,5.2,5.4,5.1
Petal Width,0.2,0.2,0.2,0.2,0.2,0.4,0.3,0.2,0.2,0.1,...,1.8,2.1,2.4,2.3,2.3,2.5,2.3,2.0,2.3,1.8
Species,setosa,setosa,setosa,setosa,setosa,setosa,setosa,setosa,setosa,setosa,...,virginica,virginica,virginica,virginica,virginica,virginica,virginica,virginica,virginica,virginica

#### Saving a dataframe into a csv
we can save a dataframe into a csv file using to_csv method

In [424]:
df.to_csv('Iris2.csv', index=False)                  # by default it takes index=True that means implicit index 
                                                     # is saved as an extra column inside the csv file

In [425]:
x = pd.read_csv('Iris2.csv')
x.head()

   Id  Sepal Length  Sepal Width  Petal Length  Petal Width Species
0   1           5.1          3.5           1.4          0.2  setosa
1   2           4.9          3.0           1.4          0.2  setosa
2   3           4.7          3.2           1.3          0.2  setosa
3   4           4.6          3.1           1.5          0.2  setosa
4   5           5.0          3.6           1.4          0.2  setosa